Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2018-05, with the labels that each got.

#511 removed unrequired str call which broke python3
  spynnaker/pyNN/models/common/eieio_spike_recorder.py
Labels: bug

#512 python3 fix
  spynnaker/pyNN/models/common/neuron_recorder.py
Labels: bug

#496 Update ArrayConnector to work with all arrays
  spynnaker/pyNN/models/neural_projections/connectors/array_connector.py
Labels: bug, enhancement

#489 Missing pynn
  spynnaker/pyNN/models/abstract_models/__init__.py
  spynnaker/pyNN/models/abstract_models/abstract_population_initializable.py
  spynnaker/pyNN/models/abstract_models/abstract_population_settable.py
  spynnaker/pyNN/models/abstract_models/abstract_settable.py
  spynnaker/pyNN/models/common/neuron_recorder.py
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_static.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py
  spynnaker/pyNN/models/pynn_population_common.py
  spynnaker/pyNN/models/recording_common.py
  spynnaker/pyNN/utilities/ranged/spynakker_ranged_dict.py
  unittests/mocks.py
  unittests/test_populations/test_population.py
  unittests/test_populations/test_vertex.py
Labels: enhancement

#518 Remove #include that wasn't needed and caused failures
  neural_modelling/src/delay_extension/delay_extension.c
  neural_modelling/src/neuron/neuron.c
  neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_mad_impl.c
  neural_modelling/src/neuron/population_table/population_table_binary_search_impl.c
  neural_modelling/src/neuron/population_table/population_table_fixed_impl.c
  neural_modelling/src/neuron/synapses.c
  neural_modelling/src/robot_motor_control/robot_motor_control.c
  neural_modelling/src/spike_source/poisson/spike_source_poisson.c
Labels: bug

#514 Filename spelling fixes
  spynnaker/pyNN/models/abstract_models/abstract_population_settable.py
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/neuron/additional_inputs/additional_input_ca2_adaptive.py
  spynnaker/pyNN/models/neuron/input_types/input_type_conductance.py
  spynnaker/pyNN/models/neuron/neuron_models/neuron_model_izh.py
  spynnaker/pyNN/models/neuron/neuron_models/neuron_model_leaky_integrate.py
  spynnaker/pyNN/models/neuron/synapse_types/synapse_type_alpha.py
  spynnaker/pyNN/models/neuron/synapse_types/synapse_type_delta.py
  spynnaker/pyNN/models/neuron/synapse_types/synapse_type_dual_exponential.py
  spynnaker/pyNN/models/neuron/synapse_types/synapse_type_exponential.py
  spynnaker/pyNN/models/neuron/threshold_types/threshold_type_maass_stochastic.py
  spynnaker/pyNN/models/neuron/threshold_types/threshold_type_static.py
  spynnaker/pyNN/utilities/ranged/__init__.py
  spynnaker/pyNN/utilities/ranged/spynnaker_ranged_dict.py
  spynnaker/pyNN/utilities/ranged/spynnaker_ranged_list.py
  unittests/model_tests/neuron/test_neural_parameter.py
Labels: bug, minor

#523 Add warnings for now that values get overwritten
  spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/all_to_all_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/multapse_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/one_to_one_connector.py
Labels: bug

#524 on no spikes returns an empty shaped array
  spynnaker/pyNN/models/common/eieio_spike_recorder.py
Labels: bug
