Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2018-03, with the labels that each got.

#475 handle set by lambda
  spynnaker/pyNN/utilities/ranged/spynakker_ranged_list.py
Labels: enhancement

#474 Multapse connector edits
  spynnaker/pyNN/models/neural_projections/connectors/multapse_connector.py
Labels: bug, enhancement

#472 One single location for mock simulator
  unittests/mocks.py
  unittests/model_tests/neuron/test_neural_parameter.py
  unittests/model_tests/neuron/test_synaptic_manager.py
  unittests/model_tests/test_connectors.py
  unittests/test_populations/test_vertex.py
Labels: enhancement

#466 Get synaptic input as array
  neural_modelling/src/neuron/input_types/input_type.h
  neural_modelling/src/neuron/input_types/input_type_conductance.h
  neural_modelling/src/neuron/input_types/input_type_current.h
  neural_modelling/src/neuron/models/neuron_model.h
  neural_modelling/src/neuron/models/neuron_model_izh_impl.c
  neural_modelling/src/neuron/models/neuron_model_lif_impl.c
  neural_modelling/src/neuron/neuron.c
  neural_modelling/src/neuron/synapse_types/synapse_types.h
  neural_modelling/src/neuron/synapse_types/synapse_types_alpha_impl.h
  neural_modelling/src/neuron/synapse_types/synapse_types_delta_impl.h
  neural_modelling/src/neuron/synapse_types/synapse_types_dual_excitatory_exponential_impl.h
  neural_modelling/src/neuron/synapse_types/synapse_types_exponential_impl.h
Labels: enhancement

#481 add maximum weight check to poisson max weight calculation
  spynnaker/pyNN/models/neuron/synaptic_manager.py
Labels: bug

#473 Updates to make the code use n_neurons for ring buffer sizing
  neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_mad_impl.c
  neural_modelling/src/neuron/synapse_row.h
  neural_modelling/src/neuron/synapses.c
  neural_modelling/src/neuron/synapses.h
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/neuron/builds/if_cond_exp_base.py
  spynnaker/pyNN/models/neuron/builds/if_cond_exp_stoc.py
  spynnaker/pyNN/models/neuron/builds/if_curr_alpha.py
  spynnaker/pyNN/models/neuron/builds/if_curr_delta.py
  spynnaker/pyNN/models/neuron/builds/if_curr_dual_exp_base.py
  spynnaker/pyNN/models/neuron/builds/if_curr_exp_base.py
  spynnaker/pyNN/models/neuron/builds/if_curr_exp_ca2_adaptive.py
  spynnaker/pyNN/models/neuron/builds/izk_cond_exp_base.py
  spynnaker/pyNN/models/neuron/builds/izk_curr_exp_base.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_static.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py
  spynnaker/pyNN/models/neuron/synapse_io/synapse_io_row_based.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  unittests/model_tests/neuron/test_synaptic_manager.py
Labels: enhancement

#483 Fixed paremeter mismatch between reading in and writing out
  neural_modelling/src/neuron/neuron.c
  spynnaker/pyNN/models/common/neuron_recorder.py
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
Labels: BLOCKER!, bug

#460 Structural plasticity
  neural_modelling/src/common/in_spikes.h
  neural_modelling/src/common/out_spikes.c
  neural_modelling/src/common/sp_structs.h
  neural_modelling/src/delay_extension/delay_extension.c
  neural_modelling/src/neuron/Makefile
  neural_modelling/src/neuron/builds/IF_cond_exp_stdp_mad_nearest_pair_additive_structural/.gitignore
  neural_modelling/src/neuron/builds/IF_cond_exp_stdp_mad_nearest_pair_additive_structural/Makefile
  neural_modelling/src/neuron/builds/IF_cond_exp_stdp_mad_pair_additive_structural/.gitignore
  neural_modelling/src/neuron/builds/IF_cond_exp_stdp_mad_pair_additive_structural/Makefile
  neural_modelling/src/neuron/builds/IF_cond_exp_structural/Makefile
  neural_modelling/src/neuron/builds/IF_curr_exp_stdp_mad_pair_additive_structural/.gitignore
  neural_modelling/src/neuron/builds/IF_curr_exp_stdp_mad_pair_additive_structural/Makefile
  neural_modelling/src/neuron/builds/IF_curr_exp_structural/Makefile
  neural_modelling/src/neuron/builds/neural_build.mk
  neural_modelling/src/neuron/c_main.c
  neural_modelling/src/neuron/neuron.c
  neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_mad_impl.c
  neural_modelling/src/neuron/plasticity/stdp/timing_dependence/timing_pair_impl.c
  neural_modelling/src/neuron/plasticity/stdp/timing_dependence/timing_recurrent_pre_stochastic_impl.c
  neural_modelling/src/neuron/plasticity/stdp/weight_dependence/weight_additive_one_term_impl.c
  neural_modelling/src/neuron/plasticity/stdp/weight_dependence/weight_additive_two_term_impl.c
  neural_modelling/src/neuron/plasticity/stdp/weight_dependence/weight_multiplicative_impl.c
  neural_modelling/src/neuron/plasticity/synapse_dynamics.h
  neural_modelling/src/neuron/plasticity/synapse_dynamics_static_impl.c
  neural_modelling/src/neuron/population_table/population_table_binary_search_impl.c
  neural_modelling/src/neuron/population_table/population_table_fixed_impl.c
  neural_modelling/src/neuron/spike_processing.c
  neural_modelling/src/neuron/spike_processing.h
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis/topographic_map_impl.c
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis_dynamics.h
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis_dynamics_static_impl.c
  neural_modelling/src/neuron/synapse_row.h
  neural_modelling/src/neuron/synapses.c
  neural_modelling/src/neuron/synapses.h
  spynnaker/pyNN/models/neuron/plasticity/structural_plasticity/__init__.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/__init__.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/abstract_synapse_dynamics_structural.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/structural_dynamics.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_static.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_static.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_stdp.py
  spynnaker/pyNN/models/neuron/synapse_io/abstract_synapse_io.py
  spynnaker/pyNN/models/neuron/synapse_io/synapse_io_row_based.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson.py
  spynnaker/pyNN/overridden_pacman_functions/graph_edge_filter.py
  unittests/model_tests/neuron/test_connection_holder.py
  unittests/model_tests/neuron/test_synaptic_manager.py
Labels: enhancement

#494 Array connector
  spynnaker/pyNN/models/neural_projections/connectors/__init__.py
  spynnaker/pyNN/models/neural_projections/connectors/array_connector.py
Labels: enhancement
