Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2019-07, with the labels that each got.

#668 Fix issues with synapse_info for n_neurons > 255
  spynnaker/pyNN/models/neuron/synaptic_manager.py
Labels: bug

#637 reimplented get_max_atoms_per_core
  spynnaker/pyNN/models/neuron/master_pop_table_generators/master_pop_table_as_binary_search.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  spynnaker/pyNN/models/spike_source/spike_source_array_vertex.py
  spynnaker/pyNN/models/utility_models/delay_extension_vertex.py
Labels: bug

#623 Sane data specification region API types
  neural_modelling/src/delay_extension/delay_extension.c
  neural_modelling/src/neuron/c_main.c
  neural_modelling/src/robot_motor_control/robot_motor_control.c
  neural_modelling/src/spike_source/poisson/spike_source_poisson.c
  neural_modelling/src/synapse_expander/delay_expander.c
  neural_modelling/src/synapse_expander/synapse_expander.c
Labels: enhancement, minor

#672 Fix to the indexing of synapse info
  spynnaker/pyNN/models/neuron/synaptic_manager.py
Labels: bug

#673 Readthedocs
  doc/source/conf.py
  setup.py
Labels: BLOCKER!, enhancement

#674 Fix save
  spynnaker/pyNN/models/neural_projections/projection_application_edge.py
  spynnaker/pyNN/models/neural_projections/synapse_information.py
  spynnaker/pyNN/models/neuron/master_pop_table_generators/master_pop_table_as_binary_search.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
Labels: bug

#645 Synapse expander on chip kernel connector
  neural_modelling/makefiles/synapse_expander/delay_expander.mk
  neural_modelling/makefiles/synapse_expander/synapse_expander.mk
  neural_modelling/src/synapse_expander/common_kernel.c
  neural_modelling/src/synapse_expander/common_kernel.h
  neural_modelling/src/synapse_expander/connection_generator.c
  neural_modelling/src/synapse_expander/connection_generators/connection_generator_kernel.h
  neural_modelling/src/synapse_expander/param_generator.c
  neural_modelling/src/synapse_expander/param_generators/param_generator_kernel.h
  spynnaker/pyNN/models/neural_projections/connectors/__init__.py
  spynnaker/pyNN/models/neural_projections/connectors/abstract_generate_connector_on_machine.py
  spynnaker/pyNN/models/neural_projections/connectors/kernel_connector.py
Labels: enhancement

#671 Initial values 2
  requirements-test.txt
  spynnaker/pyNN/models/abstract_pynn_model.py
  spynnaker/pyNN/models/defaults.py
  unittests/model_tests/neuron/test_abstract_neuron_impl.py
  unittests/model_tests/neuron/test_defaults.py
  unittests/test_populations/test_vertex.py
Labels: enhancement

#669 Better reset support
  neural_modelling/src/delay_extension/delay_extension.c
  neural_modelling/src/neuron/c_main.c
  neural_modelling/src/robot_motor_control/robot_motor_control.c
  neural_modelling/src/spike_source/poisson/spike_source_poisson.c
  spynnaker/pyNN/abstract_spinnaker_common.py
  spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/all_to_all_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/array_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/csa_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/distance_dependent_probability_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_number_post_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_number_pre_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_probability_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/from_list_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/index_based_probability_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/multapse_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/one_to_one_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/small_world_connector.py
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/neuron/implementations/ranged_dict_vertex_slice.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/abstract_synapse_dynamics.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_static.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_static.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  spynnaker/pyNN/models/pynn_population_common.py
  spynnaker/pyNN/spynnaker_simulator_interface.py
  spynnaker/pyNN/utilities/spynnaker_failed_state.py
  unittests/mocks.py
  unittests/utilities_tests/test_spinnaker_main_interface.py
Labels: bug, enhancement

#664 Python3 pushbot
  spynnaker/pyNN/protocols/munich_io_ethernet_protocol.py
Labels: bug

#678 exclude csa
  requirements.txt
  spynnaker/pyNN/models/neural_projections/connectors/csa_connector.py
Labels: enhancement

#662 Part rig
  spynnaker/pyNN/spynnaker.cfg
Labels: enhancement

#685 Emergency fix: make sure tests can run in parallel
  unittests/model_tests/neuron/test_neural_parameter.py
Labels: BLOCKER!, bug

#688 Deal with compiler warnings for null arguments to spin1_memcpy
  neural_modelling/src/neuron/implementations/neuron_impl_standard.h
Labels: bug, minor
