Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2019-06, with the labels that each got.

#658 Update delay_extension_vertex.py
  spynnaker/pyNN/models/utility_models/delay_extension_vertex.py
Labels: bug

#656 get_existing_xys_on_board
  spynnaker/pyNN/abstract_spinnaker_common.py
Labels: enhancement

#659 Fix csa random test
  unittests/connector_tests/test_csa_connector.py
Labels: bug

#632 Faster from list
  spynnaker/pyNN/models/neural_projections/connectors/from_list_connector.py
  unittests/connector_tests/test_from_list_connector.py
Labels: enhancement

#548 Citation
  CITATION.cff
  MANIFEST.in
  pypi_to_import
  requirements.txt
  setup.py
  spynnaker/_version.py
Labels: enhancement

#641 Speed up data in
  neural_modelling/makefiles/neuron/neural_build.mk
  spynnaker/pyNN/abstract_spinnaker_common.py
  spynnaker/pyNN/models/abstract_models/abstract_accepts_incoming_synapses.py
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  unittests/model_tests/neuron/test_synaptic_manager.py
Labels: enhancement, minor

#622 The fixed impl of the pop table is broken. Remove it!
  neural_modelling/makefiles/neuron/neural_build.mk
  neural_modelling/src/neuron/population_table/population_table_fixed_impl.c
  spynnaker/pyNN/models/neuron/master_pop_table_generators/__init__.py
  spynnaker/pyNN/models/neuron/master_pop_table_generators/master_pop_table_as_2d_array.py
Labels: bug, minor

#667 Make the index order of the synapse info match the block order
  spynnaker/pyNN/models/neuron/synaptic_manager.py
Labels: bug
