Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2019-02, with the labels that each got.

#593 Enable testing with Python 3.7
  .travis.yml
Labels: BLOCKER!, bug

#539 Updated to avoid issues of wrap around of timer
  neural_modelling/src/delay_extension/delay_extension.c
  neural_modelling/src/neuron/c_main.c
  neural_modelling/src/neuron/neuron.c
  neural_modelling/src/neuron/neuron.h
  neural_modelling/src/spike_source/poisson/spike_source_poisson.c
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
  spynnaker/pyNN/models/utility_models/delay_extension_vertex.py
Labels: enhancement

#564 Fix so that "make SPYNNAKER_DEBUG=DEBUG" actually works
  neural_modelling/src/neuron/implementations/neuron_impl.h
  neural_modelling/src/neuron/implementations/neuron_impl_semd.h
  neural_modelling/src/neuron/implementations/neuron_impl_standard.h
  neural_modelling/src/neuron/neuron.c
  neural_modelling/src/neuron/neuron.h
  neural_modelling/src/neuron/synapses.c
Labels: bug

#568 Fixes to allow Poisson to run forever
  spynnaker/pyNN/connections/spynnaker_poisson_control_connection.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
Labels: bug

#576 Jenkins
  neural_modelling/src/neuron/spike_processing.c
  spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/csa_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_number_post_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_number_pre_connector.py
  spynnaker/pyNN/models/neuron/implementations/struct.py
  unittests/mocks.py
  unittests/model_tests/test_connectors.py
Labels: bug, enhancement

#595 Remove synapse type header as not now needed
  neural_modelling/makefiles/neuron/neural_build.mk
  neural_modelling/src/neuron/additional_inputs/additional_input_ca2_adaptive_impl.h
  neural_modelling/src/neuron/plasticity/stdp/maths.h
Labels: bug
