Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2019-08, with the labels that each got.

#665 Fixed number connectors on machine
  neural_modelling/src/synapse_expander/connection_generator.c
  neural_modelling/src/synapse_expander/connection_generators/connection_generator_fixed_post.h
  neural_modelling/src/synapse_expander/connection_generators/connection_generator_fixed_pre.h
  neural_modelling/src/synapse_expander/connection_generators/connection_generator_fixed_prob.h
  neural_modelling/src/synapse_expander/connection_generators/connection_generator_fixed_total.h
  spynnaker/pyNN/models/neural_projections/connectors/abstract_generate_connector_on_machine.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_number_post_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_number_pre_connector.py
Labels: enhancement

#670 Fixed prob connector fix
  spynnaker/pyNN/models/neural_projections/connectors/fixed_probability_connector.py
Labels: bug

#676 Spike source poisson changes
  neural_modelling/src/common/maths-util.h
  neural_modelling/src/spike_source/poisson/profile_tags.h
  neural_modelling/src/spike_source/poisson/spike_source_poisson.c
  spynnaker/pyNN/models/spike_source/spike_source_poisson_machine_vertex.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
Labels: bug, enhancement

#680 fixing bug with delays and provenance data items
  spynnaker/pyNN/models/utility_models/delays/delay_extension_machine_vertex.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py
Labels: bug

#683 Plasticity izhikevich binaries
  neural_modelling/makefiles/neuron/IZK_cond_exp_stdp_mad_pair_additive/Makefile
  neural_modelling/makefiles/neuron/IZK_curr_exp_stdp_mad_pair_additive/Makefile
  neural_modelling/makefiles/neuron/Makefile
Labels: enhancement, minor

#691 Match simulation API
  neural_modelling/src/robot_motor_control/robot_motor_control.c
Labels: bug

#692 Fix poisson
  neural_modelling/src/spike_source/poisson/spike_source_poisson.c
Labels: bug

#693 Fix slow rate live setting
  neural_modelling/src/spike_source/poisson/spike_source_poisson.c
Labels: bug

#689 Make synapse printing code inside LOG_DEBUG work again
  neural_modelling/makefiles/neuron/neural_build.mk
  neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_mad_impl.c
Labels: bug, minor

#694 5.0.1
  requirements.txt
  setup.py
  spynnaker/_version.py
Labels: enhancement
