Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2019-11, with the labels that each got.

#724 Put function call arguments in the correct order
  spynnaker/pyNN/spynnaker_external_device_plugin_manager.py
Labels: bug

#726 calc recordered variable per slice/ machinevertex
  spynnaker/pyNN/models/common/neuron_recorder.py
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
Labels: bug

#729 Fix for when a core has an empty spike_times list
  spynnaker/pyNN/models/common/eieio_spike_recorder.py
Labels: bug

#731 Fix for integration tests with unusual spike source input
  spynnaker/pyNN/models/common/eieio_spike_recorder.py
Labels: bug

#727 Fix vogels
  neural_modelling/src/neuron/plasticity/stdp/timing_dependence/timing_vogels_2011_impl.c
Labels: bug

#710 cherry picked app prov folder vs system folder
  spynnaker/pyNN/models/utility_models/synapse_expander/synapse_expander.xml
Labels: enhancement

#733 stop changing one label and using another.
  spynnaker/pyNN/connections/spynnaker_poisson_control_connection.py
Labels: bug

#742 indexes_to_record not used here.
  spynnaker/pyNN/models/recording_common.py
Labels: enhancement, minor

#741 One conversion site
  spynnaker/pyNN/models/common/neuron_recorder.py
  spynnaker/pyNN/models/neural_projections/connectors/abstract_generate_connector_on_machine.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_probability_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/kernel_connector.py
  spynnaker/pyNN/models/neuron/generator_data.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
  spynnaker/pyNN/models/utility_models/delays/delay_generator_data.py
  spynnaker/pyNN/utilities/utility_calls.py
Labels: enhancement

#748 Compare milliseconds to milliseconds, not ticks
  spynnaker/pyNN/models/pynn_projection_common.py
Labels: bug
