Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2019-05, with the labels that each got.

#577 Extractor2
  spynnaker/pyNN/models/common/eieio_spike_recorder.py
  spynnaker/pyNN/models/common/multi_spike_recorder.py
  spynnaker/pyNN/models/common/neuron_recorder.py
  spynnaker/pyNN/models/pynn_projection_common.py
  spynnaker/pyNN/overridden_pacman_functions/spynnaker_data_specification_writer.py
Labels: enhancement

#580 Sdram per timestep
  spynnaker/pyNN/external_devices_models/munich_spinnaker_link_motor_device.py
  spynnaker/pyNN/models/common/multi_spike_recorder.py
  spynnaker/pyNN/models/common/neuron_recorder.py
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/neuron/master_pop_table_generators/master_pop_table_as_binary_search.py
  spynnaker/pyNN/models/neuron/population_machine_vertex.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  spynnaker/pyNN/models/spike_source/spike_source_array.py
  spynnaker/pyNN/models/spike_source/spike_source_array_vertex.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_machine_vertex.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
  spynnaker/pyNN/models/utility_models/delay_extension_vertex.py
  spynnaker/pyNN/models/utility_models/spike_injector.py
  spynnaker/pyNN/models/utility_models/spike_injector_vertex.py
  spynnaker/pyNN/overridden_pacman_functions/algorithms_metadata.xml
  spynnaker/pyNN/overridden_pacman_functions/spynnaker_data_specification_writer.py
  unittests/model_tests/neuron/test_neuron_recorder.py
Labels: help wanted

#650 Fix report writing for python 3
  spynnaker/pyNN/models/neuron/plasticity/stdp/common/plasticity_helpers.py
Labels: bug

#651 Move negation of timescale factor into Python
  neural_modelling/src/neuron/threshold_types/threshold_type_maass_stochastic.h
  spynnaker/pyNN/models/neuron/threshold_types/threshold_type_maass_stochastic.py
Labels: bug

#581 Use sdp directly for live input
  spynnaker/pyNN/connections/spynnaker_poisson_control_connection.py
  spynnaker/pyNN/models/utility_models/spike_injector.py
  spynnaker/pyNN/models/utility_models/spike_injector_vertex.py
  spynnaker/pyNN/spynnaker_external_device_plugin_manager.py
Labels: enhancement

#582 Add robot control types
  neural_modelling/src/neuron/threshold_types/threshold_type_external_device_control.h
  spynnaker/pyNN/external_devices_models/abstract_multicast_controllable_device.py
  spynnaker/pyNN/external_devices_models/push_bot/abstract_push_bot_output_device.py
  spynnaker/pyNN/external_devices_models/push_bot/push_bot_ethernet/push_bot_ethernet_device.py
  spynnaker/pyNN/external_devices_models/threshold_type_multicast_device_control.py
Labels: enhancement

#590 Deal with a zero rate SSPoisson case correctly
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
Labels: bug

#624 Compare using both the max and the min, otherwise mixed cases are missed
  spynnaker/pyNN/models/neural_projections/connectors/from_list_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/one_to_one_connector.py
  spynnaker/pyNN/models/pynn_projection_common.py
  unittests/mocks.py
Labels: bug

#625 Deal with input arrays in generate_weights and generate_delays correctly
  spynnaker/pyNN/models/neural_projections/connectors/from_list_connector.py
Labels: bug

#610 Use the struct parameter rather than the global value
  neural_modelling/src/spike_source/poisson/spike_source_poisson.c
Labels: bug

#655 Fix to get round error when delay is a RandomDistribution
  spynnaker/pyNN/models/pynn_projection_common.py
Labels: bug
