Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2019-10, with the labels that each got.

#696 only save time_scale_factor in config object
  spynnaker/pyNN/abstract_spinnaker_common.py
Labels: enhancement

#715 fixed incorrect import from collections.abc
  setup.py
  spynnaker/pyNN/external_devices_models/external_device_lif_control_vertex.py
  spynnaker/pyNN/models/abstract_pynn_model.py
  spynnaker/pyNN/models/common/neuron_recorder.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  spynnaker/pyNN/models/recording_common.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py
  spynnaker/pyNN/utilities/extracted_data.py
Labels: bug

#703 Fix poisson sender
  neural_modelling/src/neuron/threshold_types/threshold_type_external_device_control.h
  spynnaker/pyNN/connections/ethernet_control_connection.py
  spynnaker/pyNN/connections/spynnaker_poisson_control_connection.py
  spynnaker/pyNN/external_devices_models/external_device_lif_control.py
  spynnaker/pyNN/external_devices_models/external_device_lif_control_vertex.py
  spynnaker/pyNN/spynnaker_external_device_plugin_manager.py
Labels: bug

#713 prefix never used so NUKE!
  spynnaker/pyNN/abstract_spinnaker_common.py
  spynnaker/pyNN/models/pynn_population_common.py
  spynnaker/pyNN/spynnaker_external_device_plugin_manager.py
  unittests/mocks.py
Labels: bug

#705 Constant
  spynnaker/pyNN/external_devices_models/munich_spinnaker_link_motor_device.py
  spynnaker/pyNN/external_devices_models/push_bot/push_bot_ethernet/push_bot_retina_connection.py
  spynnaker/pyNN/external_devices_models/push_bot/push_bot_ethernet/push_bot_wifi_connection.py
  spynnaker/pyNN/models/common/eieio_spike_recorder.py
  spynnaker/pyNN/models/common/multi_spike_recorder.py
  spynnaker/pyNN/models/common/neuron_recorder.py
  spynnaker/pyNN/models/common/recording_utils.py
  spynnaker/pyNN/models/neural_projections/connectors/abstract_generate_connector_on_machine.py
  spynnaker/pyNN/models/neural_projections/connectors/all_to_all_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_number_post_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_number_pre_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_probability_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/kernel_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/multapse_connector.py
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/neuron/generator_data.py
  spynnaker/pyNN/models/neuron/implementations/abstract_standard_neuron_component.py
  spynnaker/pyNN/models/neuron/implementations/struct.py
  spynnaker/pyNN/models/neuron/master_pop_table_generators/master_pop_table_as_binary_search.py
  spynnaker/pyNN/models/neuron/neuron_models/abstract_neuron_model.py
  spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/timing_dependence_pfister_spike_triplet.py
  spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/timing_dependence_recurrent.py
  spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/timing_dependence_spike_nearest_pair.py
  spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/timing_dependence_spike_pair.py
  spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/timing_dependence_vogels_2011.py
  spynnaker/pyNN/models/neuron/plasticity/stdp/weight_dependence/weight_dependence_additive.py
  spynnaker/pyNN/models/neuron/plasticity/stdp/weight_dependence/weight_dependence_additive_triplet.py
  spynnaker/pyNN/models/neuron/plasticity/stdp/weight_dependence/weight_dependence_multiplicative.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
  spynnaker/pyNN/models/neuron/synapse_io/synapse_io_row_based.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py
  spynnaker/pyNN/models/utility_models/delays/delay_generator_data.py
  spynnaker/pyNN/utilities/constants.py
Labels: enhancement, minor

#707 Synapse expander bug
  neural_modelling/src/synapse_expander/delay_expander.c
  spynnaker/pyNN/models/neural_projections/connectors/fixed_number_post_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_number_pre_connector.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py
  spynnaker/pyNN/models/utility_models/delays/delay_generator_data.py
Labels: bug

#719 Pynn7 cleanup
  spynnaker/pyNN/models/pynn_population_common.py
  spynnaker/pyNN/models/recording_common.py
Labels: enhancement

#718 Projections on popviews
  neural_modelling/src/synapse_expander/connection_generators/connection_generator_all_to_all.h
  neural_modelling/src/synapse_expander/connection_generators/connection_generator_fixed_post.h
  neural_modelling/src/synapse_expander/connection_generators/connection_generator_fixed_prob.h
  neural_modelling/src/synapse_expander/connection_generators/connection_generator_one_to_one.h
  spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/all_to_all_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/distance_dependent_probability_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_number_post_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_number_pre_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_probability_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/one_to_one_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/small_world_connector.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  spynnaker/pyNN/models/pynn_projection_common.py
  unittests/connector_tests/test_csa_connector.py
  unittests/model_tests/neuron/test_synaptic_manager.py
  unittests/model_tests/test_connectors.py
Labels: enhancement

#717 sEMD updates
  neural_modelling/makefiles/neuron/IF_curr_exp_sEMD/Makefile
  neural_modelling/src/neuron/implementations/neuron_impl_semd.h
  neural_modelling/src/neuron/synapse_types/synapse_types_semd_impl.h
  spynnaker/pyNN/models/neuron/builds/if_curr_exp_semd_base.py
  spynnaker/pyNN/models/neuron/synapse_types/__init__.py
  spynnaker/pyNN/models/neuron/synapse_types/synapse_type_semd.py
Labels: enhancement
