Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2019-03, with the labels that each got.

#525 Move weights and delays
  spynnaker/pyNN/models/neural_projections/connectors/__init__.py
  spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/abstract_generate_connector_on_machine.py
  spynnaker/pyNN/models/neural_projections/connectors/all_to_all_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/array_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/csa_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/distance_dependent_probability_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_number_post_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_number_pre_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_probability_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/from_file_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/from_list_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/index_based_probability_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/multapse_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/one_to_one_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/small_world_connector.py
  spynnaker/pyNN/models/neural_projections/synapse_information.py
  spynnaker/pyNN/models/neuron/generator_data.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/abstract_synapse_dynamics.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py
  spynnaker/pyNN/models/neuron/synapse_io/synapse_io_row_based.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  spynnaker/pyNN/models/pynn_projection_common.py
  spynnaker/pyNN/models/utility_models/delay_extension_vertex.py
  spynnaker/pyNN/models/utility_models/delay_generator_data.py
  unittests/connector_tests/__init__.py
  unittests/connector_tests/test_from_list_connector.py
  unittests/model_tests/neuron/test_synaptic_manager.py
  unittests/model_tests/test_connectors.py
Labels: bug

#567 Fix so that multiple connectors on the same edge behave correctly
  spynnaker/pyNN/models/neural_projections/projection_machine_edge.py
Labels: bug

#606 Throw an exception if requested number of synapses is too large
  spynnaker/pyNN/models/neural_projections/connectors/multapse_connector.py
Labels: bug

#609 improved error with virtual machines
  spynnaker/pyNN/models/neuron/connection_holder.py
Labels: minor

#608 UGLY HACK!
  unittests/model_tests/neuron/test_synaptic_manager.py
Labels: bug

#611 Upgrade to Xenial (gcc 4.9, etc) and colorize the output of gcc
  .travis.yml
Labels: minor

#614 A four character fix. Oops.
  spynnaker/pyNN/models/neural_projections/connectors/from_list_connector.py
Labels: bug

#594 Deprecation warning
  setup.py
  spynnaker/pyNN/external_devices_models/external_device_lif_control_vertex.py
  spynnaker/pyNN/models/abstract_pynn_model.py
  spynnaker/pyNN/models/common/neuron_recorder.py
  spynnaker/pyNN/models/defaults.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  spynnaker/pyNN/models/recording_common.py
  spynnaker/pyNN/models/utility_models/delay_extension_vertex.py
  spynnaker/pyNN/utilities/extracted_data.py
Labels: enhancement

#588 Move label=None check prior to sending to vertex
  spynnaker/pyNN/models/pynn_population_common.py
Labels: bug
