Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2020-02, with the labels that each got.

#774 Reduce unneeded abstraction
  spynnaker/pyNN/models/neuron/master_pop_table.py
  spynnaker/pyNN/models/neuron/master_pop_table_generators/__init__.py
  spynnaker/pyNN/models/neuron/master_pop_table_generators/abstract_master_pop_table_factory.py
  spynnaker/pyNN/models/neuron/synapse_io.py
  spynnaker/pyNN/models/neuron/synapse_io/__init__.py
  spynnaker/pyNN/models/neuron/synapse_io/abstract_synapse_io.py
  spynnaker/pyNN/models/neuron/synapse_io/max_row_info.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  spynnaker/pyNN/spynnaker.cfg
  unittests/model_tests/neuron/test_synapse_io.py
  unittests/model_tests/neuron/test_synaptic_manager.py
Labels: minor

#777 Generate the inverse CDF lut as a numpy array
  spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/timing_dependence_recurrent.py
Labels: enhancement, minor

#778 Use math magic and numpy magic to compute LUTs efficiently
  spynnaker/pyNN/models/neuron/plasticity/stdp/common/plasticity_helpers.py
  spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/timing_dependence_vogels_2011.py
Labels: enhancement, minor

#770 Remove pynn7 hacks
  requirements.txt
  spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/abstract_generate_connector_on_machine.py
  spynnaker/pyNN/models/neural_projections/connectors/kernel_connector.py
  spynnaker/pyNN/models/neural_projections/projection_machine_edge.py
  spynnaker/pyNN/models/neural_projections/synapse_information.py
  spynnaker/pyNN/models/neuron/implementations/struct.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  spynnaker/pyNN/models/pynn_projection_common.py
  spynnaker/pyNN/spynnaker_simulator_interface.py
  spynnaker/pyNN/utilities/random_stats/__init__.py
  spynnaker/pyNN/utilities/random_stats/random_stats_binomial_impl.py
  spynnaker/pyNN/utilities/random_stats/random_stats_exponential_impl.py
  spynnaker/pyNN/utilities/random_stats/random_stats_gamma_impl.py
  spynnaker/pyNN/utilities/random_stats/random_stats_log_normal_impl.py
  spynnaker/pyNN/utilities/random_stats/random_stats_normal_clipped_impl.py
  spynnaker/pyNN/utilities/random_stats/random_stats_normal_impl.py
  spynnaker/pyNN/utilities/random_stats/random_stats_poisson_impl.py
  spynnaker/pyNN/utilities/random_stats/random_stats_randint_impl.py
  spynnaker/pyNN/utilities/random_stats/random_stats_scipy_impl.py
  spynnaker/pyNN/utilities/random_stats/random_stats_uniform_impl.py
  spynnaker/pyNN/utilities/random_stats/random_stats_vonmises_impl.py
  spynnaker/pyNN/utilities/ranged/spynnaker_ranged_list.py
  spynnaker/pyNN/utilities/spynnaker_failed_state.py
  spynnaker/pyNN/utilities/utility_calls.py
  unittests/mocks.py
  unittests/model_tests/neuron/test_synaptic_manager.py
  unittests/utilities_tests/test_spinnaker_main_interface.py
Labels: enhancement

#734 appears to work so using try except
  unittests/connector_tests/test_csa_connector.py
Labels: enhancement

#750 fix incorrect spelling
  spynnaker/pyNN/models/neuron/structural_plasticity/synaptogenesis/elimination/random_by_weight_elimination.py
Labels: minor

#764 Updates to IFCurrDelta, make it work for ts=0.1
  neural_modelling/makefiles/neuron/IF_curr_delta/Makefile
  neural_modelling/src/neuron/input_types/input_type_delta.h
  neural_modelling/src/neuron/synapse_types/synapse_types_delta_impl.h
  spynnaker/pyNN/models/neuron/builds/if_curr_delta.py
  spynnaker/pyNN/models/neuron/input_types/__init__.py
  spynnaker/pyNN/models/neuron/input_types/input_type_delta.py
Labels: bug, enhancement

#784 fixed @rowleya pre optimisation.
  neural_modelling/src/neuron/neuron_recording.c
Labels: EVIL VANQUISHED, instigator of evil

#775 Allocate the right size!
  neural_modelling/src/synapse_expander/param_generator.c
Labels: bug

#735 Fix injection
  spynnaker/pyNN/models/utility_models/spike_injector/spike_injector_vertex.py
Labels: bug

#785 Rename kernel parameters for starts & steps to be less confusing
  spynnaker/pyNN/models/neural_projections/connectors/kernel_connector.py
Labels: minor

#786 Kernel uint32 fix
  neural_modelling/src/synapse_expander/common_kernel.c
  neural_modelling/src/synapse_expander/common_kernel.h
Labels: bug

#788 More efficient division algorithm
  neural_modelling/src/synapse_expander/common_kernel.c
Labels: bug

#787 overrides is now ONLY in spinutils!
  spynnaker/pyNN/models/neural_projections/connectors/kernel_connector.py
  spynnaker/pyNN/models/neuron/abstract_pynn_neuron_model.py
  spynnaker/pyNN/models/neuron/structural_plasticity/synaptogenesis/elimination/random_by_weight_elimination.py
  spynnaker/pyNN/models/neuron/structural_plasticity/synaptogenesis/formation/distance_dependent_formation.py
  spynnaker/pyNN/models/neuron/structural_plasticity/synaptogenesis/partner_selection/last_neuron_selection.py
  spynnaker/pyNN/models/neuron/structural_plasticity/synaptogenesis/partner_selection/random_selection.py
Labels: enhancement

#790 10 randon tries is enough after 2 years
  unittests/model_tests/test_connectors.py
Labels: enhancement

#791 Use spinnutils Socket Address
  spynnaker/pyNN/spynnaker_external_device_plugin_manager.py
Labels: enhancement

#740 Treat weight_scale as S1615 rather than INT32
  neural_modelling/src/synapse_expander/matrix_generator.c
  neural_modelling/src/synapse_expander/matrix_generator.h
  neural_modelling/src/synapse_expander/synapse_expander.c
  spynnaker/pyNN/models/neuron/synaptic_manager.py
Labels: bug
