Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2020-09, with the labels that each got.

#799 Do the correct calculation for partitioning
  neural_modelling/src/synapse_expander/common_kernel.c
  neural_modelling/src/synapse_expander/connection_generators/connection_generator_kernel.h
  neural_modelling/src/synapse_expander/matrix_generator.c
  neural_modelling/src/synapse_expander/param_generators/param_generator_kernel.h
  spynnaker/pyNN/models/neural_projections/connectors/kernel_connector.py
Labels: bug

#860 Determinism agdr
  neural_modelling/makefiles/neuron/Makefile
  neural_modelling/src/delay_extension/delay_extension.c
  neural_modelling/src/neuron/bit_field_filter.h
  neural_modelling/src/neuron/c_main.c
  neural_modelling/src/neuron/implementations/neuron_impl.h
  neural_modelling/src/neuron/implementations/neuron_impl_external_devices.h
  neural_modelling/src/neuron/implementations/neuron_impl_standard.h
  neural_modelling/src/neuron/neuron.c
  neural_modelling/src/neuron/neuron.h
  neural_modelling/src/neuron/neuron_recording.c
  neural_modelling/src/neuron/neuron_recording.h
  neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_mad_impl.c
  neural_modelling/src/neuron/spike_processing.c
  neural_modelling/src/neuron/spike_processing.h
  neural_modelling/src/neuron/synapses.c
  neural_modelling/src/neuron/synapses.h
  neural_modelling/src/spike_source/poisson/spike_source_poisson.c
  spynnaker/pyNN/external_devices_models/munich_spinnaker_link_motor_device.py
  spynnaker/pyNN/models/common/neuron_recorder.py
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/neuron/implementations/neuron_impl_standard.py
  unittests/model_tests/neuron/test_neuron_recorder.py
Labels: enhancement

#874 spin1_wfi() provided by FEC
  neural_modelling/src/common/spin1-wfi.h
  neural_modelling/src/neuron/neuron_recording.c
  neural_modelling/src/neuron/neuron_recording.h
  neural_modelling/src/spike_source/poisson/spike_source_poisson.c
Labels: enhancement, minor

#877 Fix progress bar "error"
  spynnaker/pyNN/extra_algorithms/on_chip_bit_field_generator.py
Labels: minor

#873 fix for bitfields
  neural_modelling/src/neuron/population_table/population_table_binary_search_impl.c
Labels: BLOCKER!, bug

#863 kfixes the key issue for filtered delays
  neural_modelling/src/delay_extension/delay_extension.c
  neural_modelling/src/delay_extension/delay_extension.h
  spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py
Labels: bug, enhancement

#875 Remove timeout from test
  unittests/model_tests/neuron/test_get_max_synapses.py
Labels: EVIL VANQUISHED

#879 makes mars64 seeds to be checked by a centeral code block
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
  spynnaker/pyNN/utilities/utility_calls.py
Labels: bug, enhancement, minor

#880 Don't log provenance data as BLOB!
  spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py
Labels: bug

#851 write iobuf so mode debug picks these up
  spynnaker/pyNN/abstract_spinnaker_common.py
  spynnaker/pyNN/extra_algorithms/algorithms_metadata.xml
  spynnaker/pyNN/extra_algorithms/on_chip_bit_field_generator.py
  spynnaker/pyNN/extra_algorithms/spynnaker_machine_bit_field_router_compressor.py
  spynnaker/pyNN/spynnaker.cfg
Labels: enhancement

#824 Revert previous expander fix (which caused problems) and try another method
  neural_modelling/src/synapse_expander/connection_generators/connection_generator_fixed_pre.h
  neural_modelling/src/synapse_expander/delay_expander.c
  spynnaker/pyNN/models/neural_projections/connectors/fixed_number_pre_connector.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py
  spynnaker/pyNN/models/utility_models/delays/delay_generator_data.py
Labels: bug

#884 use max_spikes_per_ts from spike_source_poisson
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
Labels: enhancement

#842 Determism
  neural_modelling/Makefile
  neural_modelling/src/common/in_spikes.h
  neural_modelling/src/delay_extension/delay_extension.c
  neural_modelling/src/delay_extension/delay_extension.h
  neural_modelling/src/neuron/bit_field_filter.h
  neural_modelling/src/neuron/c_main.c
  neural_modelling/src/neuron/implementations/neuron_impl_external_devices.h
  neural_modelling/src/neuron/implementations/neuron_impl_standard.h
  neural_modelling/src/neuron/neuron.c
  neural_modelling/src/neuron/neuron.h
  neural_modelling/src/neuron/neuron_recording.c
  neural_modelling/src/neuron/neuron_recording.h
  neural_modelling/src/neuron/plasticity/stdp/post_events.h
  neural_modelling/src/neuron/spike_processing.c
  neural_modelling/src/neuron/spike_processing.h
  neural_modelling/src/neuron/synapses.c
  neural_modelling/src/neuron/synapses.h
  neural_modelling/src/robot_motor_control/robot_motor_control.c
  neural_modelling/src/spike_source/poisson/spike_source_poisson.c
  requirements-test.txt
  requirements.txt
  spynnaker/pyNN/external_devices_models/external_device_lif_control.py
  spynnaker/pyNN/external_devices_models/external_device_lif_control_vertex.py
  spynnaker/pyNN/external_devices_models/munich_spinnaker_link_motor_device.py
  spynnaker/pyNN/extra_algorithms/redundant_packet_count_report.py
  spynnaker/pyNN/extra_algorithms/synapse_expander.py
  spynnaker/pyNN/models/common/neuron_recorder.py
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/neuron/abstract_pynn_neuron_model.py
  spynnaker/pyNN/models/neuron/abstract_pynn_neuron_model_standard.py
  spynnaker/pyNN/models/neuron/population_machine_vertex.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_machine_vertex.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_machine_vertex.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py
  spynnaker/pyNN/spynnaker.cfg
  unittests/mocks.py
  unittests/model_tests/neuron/test_neuron_recorder.py
  unittests/model_tests/neuron/test_synaptic_manager.py
  unittests/test_populations/test_vertex.py
Labels: enhancement

#889 Correct import style
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py
Labels: minor

#890 Switch scaling to using u3232 instead of s1615
  neural_modelling/src/synapse_expander/matrix_generator.c
  neural_modelling/src/synapse_expander/matrix_generator.h
  neural_modelling/src/synapse_expander/synapse_expander.c
  spynnaker/pyNN/models/neuron/synaptic_manager.py
Labels: bug, enhancement
