Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2020-08, with the labels that each got.

#853 Remove gnu functions
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis/formation/formation_distance_dependent_impl.h
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis/partner_selection/last_neuron_selection_impl.h
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis/sp_structs.h
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis/topographic_map_impl.c
  spynnaker/pyNN/models/neuron/structural_plasticity/synaptogenesis/formation/distance_dependent_formation.py
Labels: enhancement

#854 Cross link to dependencies (and generate a spynnaker.tag file)
  .ratexcludes
  .travis.yml
  neural_modelling/.common_template.tag
  neural_modelling/.fec_template.tag
  neural_modelling/.gitignore
  neural_modelling/.sllt_template.tag
  neural_modelling/Doxyfile
  neural_modelling/Makefile
Labels: enhancement

#855 rejig to make external device lif control better for tdma
  neural_modelling/makefiles/neuron/external_device_lif_control/Makefile
  neural_modelling/src/neuron/implementations/neuron_impl_external_devices.h
  neural_modelling/src/neuron/threshold_types/threshold_type_external_device_control.h
Labels: enhancement

#856 There can be only one...
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis/partner_selection/random_selection_impl.h
Labels: enhancement

#862 Add testing with Python 3.8
  .travis.yml
  setup.py
  spynnaker/pyNN/extra_algorithms/redundant_packet_count_report.py
  spynnaker/pyNN/extra_algorithms/synapse_expander.py
Labels: enhancement, minor

#847 Pre filter
  spynnaker/pyNN/extra_algorithms/__init__.py
  spynnaker/pyNN/extra_algorithms/algorithms_metadata.xml
  spynnaker/pyNN/extra_algorithms/graph_edge_filter.py
  spynnaker/pyNN/models/abstract_models/__init__.py
  spynnaker/pyNN/models/abstract_models/abstract_filterable_edge.py
  spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/from_list_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/one_to_one_connector.py
  spynnaker/pyNN/models/neural_projections/delay_afferent_application_edge.py
  spynnaker/pyNN/models/neural_projections/delay_afferent_machine_edge.py
  spynnaker/pyNN/models/neural_projections/delayed_application_edge.py
  spynnaker/pyNN/models/neural_projections/delayed_machine_edge.py
  spynnaker/pyNN/models/neural_projections/projection_application_edge.py
  spynnaker/pyNN/models/neural_projections/projection_machine_edge.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py
  spynnaker/pyNN/spynnaker.cfg
  unittests/connector_tests/test_from_list_connector.py
Labels: enhancement

#866 Binary from machine
  spynnaker/pyNN/external_devices_models/__init__.py
  spynnaker/pyNN/external_devices_models/machine_munich_motor_device.py
  spynnaker/pyNN/external_devices_models/munich_spinnaker_link_motor_device.py
  spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/from_list_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/one_to_one_connector.py
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/neuron/population_machine_vertex.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_machine_vertex.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_machine_vertex.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py
Labels: enhancement

#869 fix of reading bitfields back. seems to have got lost somewhere
  spynnaker/pyNN/extra_algorithms/on_chip_bit_field_generator.py
Labels: bug

#867 fixes https://github.com/SpiNNakerManchester/sPyNNaker/issues/865
  spynnaker/pyNN/models/pynn_population_common.py
Labels: bug

#871 Update on_chip_bit_field_generator.py
  spynnaker/pyNN/extra_algorithms/on_chip_bit_field_generator.py
Labels: BLOCKER!, bug
