Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2020-03, with the labels that each got.

#795 Edge Filtered token
  spynnaker/pyNN/overridden_pacman_functions/algorithms_metadata.xml
Labels: bug

#793 Deal with reset case with left over delayed spike
  neural_modelling/src/neuron/c_main.c
  neural_modelling/src/neuron/synapses.c
  neural_modelling/src/neuron/synapses.h
Labels: bug

#779 Filter edges correctly when using PopulationViews
  spynnaker/pyNN/models/neural_projections/projection_machine_edge.py
Labels: bug

#780 Recalculate ring buffer shifts if they're all zero
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  spynnaker/pyNN/models/pynn_projection_common.py
Labels: bug

#806 Nuke no longer required unused functions
  spynnaker/pyNN/models/common/neuron_recorder.py
  unittests/model_tests/neuron/test_neuron_recorder.py
Labels: bug

#809 Add safety check to prevent underflow in _get_max_row_length
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py
  unittests/model_tests/neuron/test_get_max_synapses.py
Labels: bug

#807 Remove incorrect timing measurement instrumentation
  spynnaker/pyNN/models/recording_common.py
Labels: bug

#810 Poisson distribution doesn't have a mu parameter...
  spynnaker/pyNN/utilities/random_stats/random_stats_poisson_impl.py
Labels: bug

#811 Fix circular dependency
  spynnaker/pyNN/models/neuron/implementations/__init__.py
  spynnaker/pyNN/models/neuron/implementations/abstract_standard_neuron_component.py
  spynnaker/pyNN/models/neuron/neuron_models/abstract_neuron_model.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
  spynnaker/pyNN/utilities/struct.py
Labels: bug

#813 Remove utterly broken test
  unittests/external_device_model_tests/__init__.py
  unittests/external_device_model_tests/test_live_spike_recorder.py
Labels: bug, minor

#768 Make FixedNumberConnectors work with PopulationViews
  neural_modelling/src/synapse_expander/connection_generators/connection_generator_fixed_post.h
  neural_modelling/src/synapse_expander/connection_generators/connection_generator_fixed_pre.h
  neural_modelling/src/synapse_expander/connection_generators/connection_generator_fixed_total.h
  spynnaker/pyNN/models/neural_projections/connectors/__init__.py
  spynnaker/pyNN/models/neural_projections/connectors/abstract_connector_supports_views_on_machine.py
  spynnaker/pyNN/models/neural_projections/connectors/all_to_all_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_number_post_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_number_pre_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_probability_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/multapse_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/one_to_one_connector.py
Labels: enhancement
