Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2020-10, with the labels that each got.

#876 Parameters sdram usage in bytes
  spynnaker/pyNN/models/neuron/synapse_dynamics/abstract_synapse_dynamics_structural.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
Labels: enhancement

#887 Slice index is not vertex index
  spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/abstract_generate_connector_on_machine.py
  spynnaker/pyNN/models/neural_projections/connectors/all_to_all_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/array_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/csa_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/distance_dependent_probability_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_number_post_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_number_pre_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_probability_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/from_list_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/index_based_probability_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/kernel_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/multapse_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/one_to_one_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/small_world_connector.py
  spynnaker/pyNN/models/neuron/generator_data.py
  spynnaker/pyNN/models/neuron/synapse_io.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py
  spynnaker/pyNN/models/utility_models/delays/delay_generator_data.py
  unittests/connector_tests/test_csa_connector.py
  unittests/connector_tests/test_from_list_connector.py
  unittests/model_tests/neuron/test_synaptic_manager.py
  unittests/model_tests/test_connectors.py
Labels: enhancement

#883 move get_ring_buffer_shifts to machine level
  spynnaker/pyNN/models/abstract_models/__init__.py
  spynnaker/pyNN/models/abstract_models/abstract_max_spikes.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  spynnaker/pyNN/models/spike_source/__init__.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_machine_vertex.py
Labels: enhancement

#888 Edge saves slices
  spynnaker/pyNN/models/neural_projections/projection_application_edge.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  unittests/model_tests/neuron/test_projection_application_edge.py
Labels: enhancement

#894 No more storage handlers
  .travis.yml
  doc/doc_requirements.txt
  doc/source/conf.py
  pypi_to_import
  requirements.txt
  setup.py
  unittests/model_tests/neuron/test_neural_parameter.py
  unittests/model_tests/neuron/test_synaptic_manager.py
  unittests/test_version.py
Labels: EVIL VANQUISHED, bug, enhancement, minor

#776 Pop based master pop table
  neural_modelling/src/bit_field_expander/bit_field_expander.c
  neural_modelling/src/neuron/bit_field_filter.h
  neural_modelling/src/neuron/c_main.c
  neural_modelling/src/neuron/population_table/population_table.h
  neural_modelling/src/neuron/population_table/population_table_binary_search_impl.c
  neural_modelling/src/neuron/spike_processing.c
  neural_modelling/src/neuron/spike_processing.h
  spynnaker/pyNN/abstract_spinnaker_common.py
  spynnaker/pyNN/extra_algorithms/algorithms_metadata.xml
  spynnaker/pyNN/extra_algorithms/connection_holder_finisher.py
  spynnaker/pyNN/extra_algorithms/spynnaker_connection_holder_generations.py
  spynnaker/pyNN/extra_algorithms/synapse_expander.py
  spynnaker/pyNN/models/abstract_models/abstract_accepts_incoming_synapses.py
  spynnaker/pyNN/models/neural_projections/delayed_application_edge.py
  spynnaker/pyNN/models/neural_projections/delayed_machine_edge.py
  spynnaker/pyNN/models/neural_projections/projection_application_edge.py
  spynnaker/pyNN/models/neural_projections/projection_machine_edge.py
  spynnaker/pyNN/models/neural_projections/synapse_information.py
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/neuron/abstract_pynn_neuron_model.py
  spynnaker/pyNN/models/neuron/connection_holder.py
  spynnaker/pyNN/models/neuron/generator_data.py
  spynnaker/pyNN/models/neuron/key_space_tracker.py
  spynnaker/pyNN/models/neuron/master_pop_table.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/abstract_plastic_synapse_dynamics.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/abstract_static_synapse_dynamics.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/abstract_synapse_dynamics.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/abstract_synapse_dynamics_structural.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_static.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_static.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_stdp.py
  spynnaker/pyNN/models/neuron/synapse_io.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  spynnaker/pyNN/models/neuron/synaptic_matrices.py
  spynnaker/pyNN/models/neuron/synaptic_matrix.py
  spynnaker/pyNN/models/neuron/synaptic_matrix_app.py
  spynnaker/pyNN/models/pynn_projection_common.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py
  spynnaker/pyNN/utilities/bit_field_utilities.py
  spynnaker/pyNN/utilities/constants.py
  unittests/model_tests/neuron/test_synapse_io.py
  unittests/model_tests/neuron/test_synaptic_manager.py
Labels: enhancement

#903 Add missing support
  spynnaker/pyNN/models/neuron/synaptic_matrix_app.py
Labels: bug

#900 spynapse_expander at the machine level
  spynnaker/pyNN/extra_algorithms/algorithms_metadata.xml
  spynnaker/pyNN/extra_algorithms/spynnaker_machine_bit_field_router_compressor.py
  spynnaker/pyNN/extra_algorithms/synapse_expander.py
  spynnaker/pyNN/models/abstract_models/__init__.py
  spynnaker/pyNN/models/abstract_models/abstract_synapse_expandable.py
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/neuron/population_machine_vertex.py
  spynnaker/pyNN/models/utility_models/delays/__init__.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_machine_vertex.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py
Labels: enhancement

#899 all or nothing for machinevertex.appvertex
  unittests/model_tests/neuron/test_synaptic_manager.py
Labels: minor

#907 Reorder bitfield loading
  neural_modelling/src/bit_field_expander/bit_field_expander.c
  neural_modelling/src/neuron/c_main.c
  neural_modelling/src/neuron/population_table/population_table.h
  neural_modelling/src/neuron/population_table/population_table_binary_search_impl.c
Labels: bug

#912 fixed and test round warning
  spynnaker/pyNN/models/pynn_population_common.py
  unittests/test_populations/test_population.py
Labels: bug

#913 Allow specification of partition id for activating live output to
  spynnaker/pyNN/spynnaker_external_device_plugin_manager.py
Labels: enhancement
