Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2020-12, with the labels that each got.

#943 add_application_entry should return a value
  spynnaker/pyNN/models/neuron/master_pop_table.py
Labels: bug

#895 doc changes
  spynnaker/pyNN/external_devices_models/push_bot/push_bot_spinnaker_link/push_bot_spinnaker_link_laser_device.py
  spynnaker/pyNN/external_devices_models/push_bot/push_bot_spinnaker_link/push_bot_spinnaker_link_led_device.py
  spynnaker/pyNN/external_devices_models/push_bot/push_bot_spinnaker_link/push_bot_spinnaker_link_motor_device.py
  spynnaker/pyNN/external_devices_models/push_bot/push_bot_spinnaker_link/push_bot_spinnaker_link_speaker_device.py
Labels: enhancement, minor

#914 Application Vertices should make sure n_atoms is an int
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py
Labels: enhancement

#950 Version binding for numpy
  doc/source/conf.py
  requirements.txt
  setup.py
Labels: BLOCKER!, bug

#952 Corrections to numpy version requirements
  requirements.txt
  setup.py
Labels: BLOCKER!, bug

#931 Use structs to access synaptic rows
  neural_modelling/src/bit_field_expander/bit_field_expander.c
  neural_modelling/src/common/neuron-typedefs.h
  neural_modelling/src/neuron/direct_synapses.c
  neural_modelling/src/neuron/direct_synapses.h
  neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_mad_impl.c
  neural_modelling/src/neuron/plasticity/synapse_dynamics.h
  neural_modelling/src/neuron/plasticity/synapse_dynamics_static_impl.c
  neural_modelling/src/neuron/population_table/population_table.h
  neural_modelling/src/neuron/population_table/population_table_binary_search_impl.c
  neural_modelling/src/neuron/spike_processing.c
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis/elimination/elimination.h
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis/elimination/elimination_random_by_weight_impl.h
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis/formation/formation.h
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis/formation/formation_distance_dependent_impl.h
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis/sp_structs.h
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis/topographic_map_impl.c
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis_dynamics.h
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis_dynamics_static_impl.c
  neural_modelling/src/neuron/synapse_row.h
  neural_modelling/src/neuron/synapses.c
  neural_modelling/src/neuron/synapses.h
  neural_modelling/src/synapse_expander/matrix_generators/matrix_generator_static.h
  neural_modelling/src/synapse_expander/matrix_generators/matrix_generator_stdp.h
Labels: EVIL VANQUISHED, enhancement, minor

#933 Enable specific documenting of __call__() methods
  doc/source/conf.py
  doc/source/index.rst
  requirements-test.txt
  spynnaker/pyNN/external_devices_models/threshold_type_multicast_device_control.py
  spynnaker/pyNN/extra_algorithms/__init__.py
  spynnaker/pyNN/extra_algorithms/connection_holder_finisher.py
  spynnaker/pyNN/extra_algorithms/graph_edge_weight_updater.py
  spynnaker/pyNN/extra_algorithms/on_chip_bit_field_generator.py
  spynnaker/pyNN/extra_algorithms/redundant_packet_count_report.py
  spynnaker/pyNN/extra_algorithms/splitter_components/splitter_abstract_pop_vertex_slice.py
  spynnaker/pyNN/extra_algorithms/splitter_components/spynnaker_splitter_partitioner.py
  spynnaker/pyNN/extra_algorithms/spynnaker_connection_holder_generations.py
  spynnaker/pyNN/extra_algorithms/spynnaker_data_specification_writer.py
  spynnaker/pyNN/extra_algorithms/spynnaker_machine_bit_field_router_compressor.py
  spynnaker/pyNN/extra_algorithms/spynnaker_neuron_network_specification_report.py
  spynnaker/pyNN/extra_algorithms/spynnaker_synaptic_matrix_report.py
  spynnaker/pyNN/extra_algorithms/synapse_expander.py
  spynnaker/pyNN/models/abstract_models/abstract_max_spikes.py
  spynnaker/pyNN/models/abstract_models/abstract_synapse_expandable.py
  spynnaker/pyNN/models/common/abstract_neuron_recordable.py
  spynnaker/pyNN/models/neural_projections/delayed_application_edge.py
  spynnaker/pyNN/models/neural_projections/projection_application_edge.py
  spynnaker/pyNN/models/neuron/input_types/input_type_current.py
  spynnaker/pyNN/models/neuron/input_types/input_type_delta.py
  spynnaker/pyNN/models/neuron/master_pop_table.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/abstract_synapse_dynamics_structural.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
  spynnaker/pyNN/models/neuron/synapse_io.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  spynnaker/pyNN/models/neuron/synaptic_matrices.py
  spynnaker/pyNN/models/neuron/synaptic_matrix.py
  spynnaker/pyNN/models/neuron/synaptic_matrix_app.py
Labels: enhancement, minor
