Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2020-11, with the labels that each got.

#910 MunichMotorDevice most functionaility moved to machine level
  spynnaker/pyNN/external_devices_models/machine_munich_motor_device.py
  spynnaker/pyNN/external_devices_models/munich_spinnaker_link_motor_device.py
Labels: enhancement

#920 Turn on github actions Python side
  .github/workflows/python_actions.yml
  .ratexcludes
  spynnaker/pyNN/external_devices_models/external_spinnaker_link_fpga_retina_device.py
  spynnaker/pyNN/external_devices_models/push_bot/abstract_push_bot_retina_device.py
  spynnaker/pyNN/models/abstract_models/__init__.py
  spynnaker/pyNN/models/abstract_models/abstract_accepts_incoming_synapses.py
  spynnaker/pyNN/models/abstract_models/abstract_has_delay_stages.py
  spynnaker/pyNN/models/abstract_models/abstract_synapse_expandable.py
  spynnaker/pyNN/models/common/neuron_recorder.py
  spynnaker/pyNN/models/neural_projections/projection_application_edge.py
  spynnaker/pyNN/models/neuron/master_pop_table.py
  spynnaker/pyNN/models/neuron/population_machine_vertex.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/abstract_synapse_dynamics_structural.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
  spynnaker/pyNN/models/neuron/synapse_io.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  spynnaker/pyNN/models/neuron/synaptic_matrices.py
  spynnaker/pyNN/models/neuron/synaptic_matrix.py
  spynnaker/pyNN/models/neuron/synaptic_matrix_app.py
  spynnaker/pyNN/models/pynn_population_common.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_machine_vertex.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py
  spynnaker/pyNN/utilities/bit_field_utilities.py
Labels: BLOCKER!, enhancement

#918 Docfix
  spynnaker/pyNN/external_devices_models/external_spinnaker_link_fpga_retina_device.py
  spynnaker/pyNN/external_devices_models/push_bot/abstract_push_bot_retina_device.py
  spynnaker/pyNN/models/abstract_models/__init__.py
  spynnaker/pyNN/models/abstract_models/abstract_accepts_incoming_synapses.py
  spynnaker/pyNN/models/abstract_models/abstract_has_delay_stages.py
  spynnaker/pyNN/models/abstract_models/abstract_synapse_expandable.py
  spynnaker/pyNN/models/common/neuron_recorder.py
  spynnaker/pyNN/models/neural_projections/projection_application_edge.py
  spynnaker/pyNN/models/neuron/master_pop_table.py
  spynnaker/pyNN/models/neuron/population_machine_vertex.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/abstract_synapse_dynamics_structural.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
  spynnaker/pyNN/models/neuron/synapse_io.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  spynnaker/pyNN/models/neuron/synaptic_matrices.py
  spynnaker/pyNN/models/neuron/synaptic_matrix.py
  spynnaker/pyNN/models/neuron/synaptic_matrix_app.py
  spynnaker/pyNN/models/pynn_population_common.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_machine_vertex.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py
  spynnaker/pyNN/utilities/bit_field_utilities.py
Labels: BLOCKER!, bug

#923 DelaySupportAdder cleanup
  spynnaker/pyNN/extra_algorithms/delay_support_adder.py
Labels: enhancement

#921 Turn on shpinx in python actions
  .github/workflows/python_actions.yml
  requirements-test.txt
Labels: enhancement

#919 Add C actions
  .github/workflows/c_actions.yml
Labels: BLOCKER!, enhancement

#924 Define a publish action
  .github/workflows/publish.yml
Labels: BLOCKER!, in progress

#917 avoid making a invalid error message
  neural_modelling/src/neuron/population_table/population_table_binary_search_impl.c
Labels: bug, enhancement

#915 moves data spec and regen data spec into the machine vertex.
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/neuron/population_machine_vertex.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_machine_vertex.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
Labels: enhancement

#930 Use structures to describe STDP config
  neural_modelling/src/neuron/plasticity/stdp/timing_dependence/timing_recurrent_dual_fsm_impl.c
  neural_modelling/src/neuron/plasticity/stdp/timing_dependence/timing_recurrent_pre_stochastic_impl.c
  neural_modelling/src/neuron/plasticity/stdp/timing_dependence/timing_vogels_2011_impl.c
  neural_modelling/src/neuron/plasticity/stdp/weight_dependence/weight_additive_one_term_impl.c
  neural_modelling/src/neuron/plasticity/stdp/weight_dependence/weight_additive_two_term_impl.c
  neural_modelling/src/neuron/plasticity/stdp/weight_dependence/weight_additive_two_term_impl.h
  neural_modelling/src/neuron/plasticity/stdp/weight_dependence/weight_multiplicative_impl.c
Labels: enhancement, minor

#932 Improved version of bitfield generation and reporting
  spynnaker/pyNN/extra_algorithms/on_chip_bit_field_generator.py
  spynnaker/pyNN/extra_algorithms/spynnaker_machine_bit_field_router_compressor.py
  spynnaker/pyNN/extra_algorithms/spynnaker_neuron_network_specification_report.py
Labels: enhancement, minor

#891 Run synchronized
  neural_modelling/src/delay_extension/delay_extension.c
  neural_modelling/src/neuron/c_main.c
  neural_modelling/src/neuron/population_table/population_table_binary_search_impl.c
  neural_modelling/src/neuron/synapses.c
  neural_modelling/src/neuron/synapses.h
  neural_modelling/src/robot_motor_control/robot_motor_control.c
  neural_modelling/src/spike_source/poisson/spike_source_poisson.c
  spynnaker/pyNN/abstract_spinnaker_common.py
Labels: enhancement

#934 Update README.md to use new badgers
  README.md
Labels: minor

#928 makes AbstractReadParametersBeforeSet apply to only machine verts
  spynnaker/pyNN/models/abstract_models/abstract_read_parameters_before_set.py
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/neuron/population_machine_vertex.py
  spynnaker/pyNN/models/pynn_population_common.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_machine_vertex.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
Labels: enhancement
