Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2020-04, with the labels that each got.

#815 Fix pause-and-resume for eprop neuron model
  neural_modelling/src/neuron/implementations/neuron_impl_eprop_adaptive.h
  neural_modelling/src/neuron/models/neuron_model_eprop_adaptive_impl.c
  spynnaker/pyNN/models/neuron/neuron_models/neuron_model_eprop_adaptive.py
Labels: bug, enhancement

#808 Report the final value of count_rewires back as provenance
  neural_modelling/src/neuron/c_main.c
  neural_modelling/src/neuron/spike_processing.c
  neural_modelling/src/neuron/spike_processing.h
  spynnaker/pyNN/models/neuron/population_machine_vertex.py
Labels: enhancement, minor

#817 Multi time step
  .travis.yml
  neural_modelling/src/neuron/implementations/neuron_impl_standard.h
  spynnaker/pyNN/external_devices_models/external_device_lif_control.py
  spynnaker/pyNN/external_devices_models/threshold_type_multicast_device_control.py
  spynnaker/pyNN/models/neuron/abstract_pynn_neuron_model_standard.py
  spynnaker/pyNN/models/neuron/additional_inputs/additional_input_ca2_adaptive.py
  spynnaker/pyNN/models/neuron/implementations/abstract_standard_neuron_component.py
  spynnaker/pyNN/models/neuron/implementations/neuron_impl_standard.py
  spynnaker/pyNN/models/neuron/input_types/input_type_conductance.py
  spynnaker/pyNN/models/neuron/input_types/input_type_current.py
  spynnaker/pyNN/models/neuron/input_types/input_type_current_semd.py
  spynnaker/pyNN/models/neuron/input_types/input_type_delta.py
  spynnaker/pyNN/models/neuron/neuron_models/abstract_neuron_model.py
  spynnaker/pyNN/models/neuron/neuron_models/neuron_model_izh.py
  spynnaker/pyNN/models/neuron/neuron_models/neuron_model_leaky_integrate_and_fire.py
  spynnaker/pyNN/models/neuron/synapse_types/synapse_type_alpha.py
  spynnaker/pyNN/models/neuron/synapse_types/synapse_type_delta.py
  spynnaker/pyNN/models/neuron/synapse_types/synapse_type_dual_exponential.py
  spynnaker/pyNN/models/neuron/synapse_types/synapse_type_exponential.py
  spynnaker/pyNN/models/neuron/synapse_types/synapse_type_semd.py
  spynnaker/pyNN/models/neuron/threshold_types/threshold_type_maass_stochastic.py
  spynnaker/pyNN/models/neuron/threshold_types/threshold_type_static.py
  unittests/test_populations/test_vertex.py
Labels: enhancement
