Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2020-06, with the labels that each got.

#825 Reload neuron parameters after setting initial value
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
Labels: bug

#657 All algorithms
  neural_modelling/Makefile
  neural_modelling/makefiles/bit_field_expander/Makefile
  neural_modelling/makefiles/neuron/neural_build.mk
  neural_modelling/src/bit_field_expander/bit_field_expander.c
  neural_modelling/src/neuron/bit_field_filter.h
  neural_modelling/src/neuron/c_main.c
  neural_modelling/src/neuron/direct_synapses.c
  neural_modelling/src/neuron/direct_synapses.h
  neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_mad_impl.c
  neural_modelling/src/neuron/plasticity/synapse_dynamics.h
  neural_modelling/src/neuron/plasticity/synapse_dynamics_static_impl.c
  neural_modelling/src/neuron/population_table/population_table.h
  neural_modelling/src/neuron/population_table/population_table_binary_search_impl.c
  neural_modelling/src/neuron/regions.h
  neural_modelling/src/neuron/spike_processing.c
  neural_modelling/src/neuron/spike_processing.h
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis/sp_structs.h
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis/topographic_map_impl.c
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis_dynamics.h
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis_dynamics_static_impl.c
  neural_modelling/src/neuron/synapses.c
  neural_modelling/src/neuron/synapses.h
  spynnaker/pyNN/abstract_spinnaker_common.py
  spynnaker/pyNN/external_devices_models/munich_spinnaker_link_retina_device.py
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/neuron/population_machine_vertex.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/abstract_synapse_dynamics_structural.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_static.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_stdp.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  spynnaker/pyNN/overridden_pacman_functions/algorithms_metadata.xml
  spynnaker/pyNN/overridden_pacman_functions/on_chip_bit_field_generator.py
  spynnaker/pyNN/overridden_pacman_functions/spynnaker_machine_bit_field_router_compressor.py
  spynnaker/pyNN/spynnaker.cfg
  spynnaker/pyNN/utilities/bit_field_utilities.py
  spynnaker/pyNN/utilities/constants.py
  spynnaker/pyNN/utilities/redundant_packet_count_report.py
  spynnaker/pyNN/utilities/utility_calls.py
Labels: enhancement

#830 Magic, with __builtin_assume_aligned()!
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis/sp_structs.h
Labels: BLOCKER!, bug

#826 Upgrade Travis Ubuntu distribution to bionic (18.04)
  .travis.yml
Labels: enhancement

#832 Recent merge showed up some places that were missing includes
  neural_modelling/src/neuron/neuron.h
  neural_modelling/src/neuron/plasticity/stdp/maths.h
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis/sp_structs.h
Labels: BLOCKER!, bug
