Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2020-01, with the labels that each got.

#760 coverage 5.0 is unusable
  .travis.yml
  requirements-test.txt
Labels: BLOCKER!

#767 Reverted safer way to get around windows permsion denied problem
  unittests/model_tests/neuron/test_neural_parameter.py
Labels: bug

#738 lots of fiddles. wee attempt to fix protocol.
  spynnaker/pyNN/abstract_spinnaker_common.py
  spynnaker/pyNN/models/abstract_models/abstract_accepts_incoming_synapses.py
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  spynnaker/pyNN/models/pynn_projection_common.py
  spynnaker/pyNN/overridden_pacman_functions/algorithms_metadata.xml
Labels: bug, enhancement

#765 Add a check that a variable can be initialized
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
Labels: bug

#769 Fix n_connections to post vertex for FixedNumberPostConnector
  spynnaker/pyNN/models/neural_projections/connectors/fixed_number_post_connector.py
  unittests/model_tests/test_connectors.py
Labels: bug
