Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2021-05, with the labels that each got.

#1069 removed dead cfg option
  unittests/test_sata_connectors/spynnaker.cfg
Labels: blocker, bug

#906 Use the new provenance reporting API where possible
  spynnaker/pyNN/external_devices_models/machine_munich_motor_device.py
  spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py
  spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/abstract_timing_dependence.py
  spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/timing_dependence_pfister_spike_triplet.py
  spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/timing_dependence_recurrent.py
  spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/timing_dependence_spike_nearest_pair.py
  spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/timing_dependence_spike_pair.py
  spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/timing_dependence_vogels_2011.py
  spynnaker/pyNN/models/neuron/plasticity/stdp/weight_dependence/abstract_weight_dependence.py
  spynnaker/pyNN/models/neuron/plasticity/stdp/weight_dependence/weight_dependence_additive.py
  spynnaker/pyNN/models/neuron/plasticity/stdp/weight_dependence/weight_dependence_additive_triplet.py
  spynnaker/pyNN/models/neuron/plasticity/stdp/weight_dependence/weight_dependence_multiplicative.py
  spynnaker/pyNN/models/neuron/population_machine_vertex.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/abstract_synapse_dynamics.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_machine_vertex.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_machine_vertex.py
  unittests/model_tests/neuron/test_neural_parameter.py
Labels: enhancement

#1070 read_router_compressor_with_bitfield_iobuf no longer used.
  spynnaker_integration_tests/test_iobuf/test_iobuf_without_during_run_flag/spynnaker.cfg
Labels: blocker, bug

#1063 Add flake8 back for spynnaker_integration_tests, spynnaker8 directories
  .github/workflows/python_actions.yml
  spynnaker8/models/connectors/multapse_connector.py
  spynnaker8/models/recorder.py
  spynnaker8/models/synapse_dynamics/timing_dependence/timing_dependence_recurrent.py
  spynnaker8/models/synapse_dynamics/timing_dependence/timing_dependence_spike_nearest_pair.py
  spynnaker8/models/synapse_dynamics/timing_dependence/timing_dependence_vogels_2011.py
  spynnaker_integration_tests/test_big_connection/test_big_connection.py
  spynnaker_integration_tests/test_many_boards/many_boards.py
  spynnaker_integration_tests/test_record_sdram/__init__.py
  spynnaker_integration_tests/test_record_sdram_no_extra_mons/__init__.py
  spynnaker_integration_tests/test_selective_recording/test_recording_on_off.py
  spynnaker_integration_tests/test_selective_recording/test_sampling.py
  spynnaker_integration_tests/test_selective_recording/test_sampling_by_compare.py
  spynnaker_integration_tests/test_stdp/test_STDP_pair_multiplicative.py
  spynnaker_integration_tests/test_struct_pl/test_structural_formation_to_full.py
  spynnaker_integration_tests/test_various/test_record_packets_per_timestep.py
Labels: minor

#1077 Move the reports to FEC
  spynnaker_integration_tests/test_debug_mode/check_debug.py
  unittests/test_using_virtual_board/test_debug_mode/test_debug.py
Labels: enhancement

#1080 Test with graphviz installed
  .github/workflows/python_actions.yml
  requirements-test.txt
  setup.py
  spynnaker/pyNN/abstract_spinnaker_common.py
  spynnaker/pyNN/extra_algorithms/spynnaker_neuron_network_specification_report.py
  unittests/test_integration_using_virtual_board/spynnaker.cfg
Labels: bug

#1083 Reset fix
  spynnaker/pyNN/abstract_spinnaker_common.py
  spynnaker/pyNN/spynnaker.cfg
  spynnaker_integration_tests/test_debug_mode/check_debug.py
  unittests/test_integration_using_virtual_board/spynnaker.cfg
  unittests/test_using_virtual_board/test_debug_mode/test_debug.py
Labels: bug, enhancement

#1084 Error when too many redraws are requested in a clipped distribution
  neural_modelling/src/synapse_expander/param_generators/param_generator_normal_clipped.h
  spynnaker_integration_tests/test_various/test_synaptic_expander.py
Labels: bug

#1075 Simplify Simulator stack
  spynnaker/pyNN/abstract_spinnaker_common.py
  spynnaker/pyNN/spynnaker_simulator_interface.py
  spynnaker/pyNN/utilities/spynnaker_failed_state.py
  spynnaker8/__init__.py
  spynnaker8/spinnaker.py
  unittests/connector_tests/test_csa_connector.py
  unittests/connector_tests/test_from_list_connector.py
  unittests/mocks.py
  unittests/model_tests/neuron/test_get_max_synapses.py
  unittests/model_tests/neuron/test_neural_parameter.py
  unittests/model_tests/neuron/test_neuron_recorder.py
  unittests/model_tests/neuron/test_spike_source/test_spike_source_array_vertex.py
  unittests/model_tests/neuron/test_synapse_io.py
  unittests/model_tests/neuron/test_synaptic_manager.py
  unittests/model_tests/test_connectors.py
  unittests/test_from_file_connector.py
  unittests/test_populations/test_population.py
  unittests/test_populations/test_vertex.py
  unittests/utilities_tests/test_spinnaker_main_interface.py
Labels: enhancement

#1042 Structural plasticity recording
  neural_modelling/makefiles/neuron/Makefile
  neural_modelling/src/neuron/c_main.c
  neural_modelling/src/neuron/implementations/neuron_impl_standard.h
  neural_modelling/src/neuron/neuron_recording.h
  neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_mad_impl.c
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis/sp_structs.h
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis/topographic_map_impl.c
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis_dynamics.h
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis_dynamics_static_impl.c
  spynnaker/pyNN/extra_algorithms/splitter_components/splitter_abstract_pop_vertex_slice.py
  spynnaker/pyNN/models/common/__init__.py
  spynnaker/pyNN/models/common/abstract_event_recordable.py
  spynnaker/pyNN/models/common/neuron_recorder.py
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/neuron/population_machine_vertex.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/abstract_synapse_dynamics_structural.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
  spynnaker/pyNN/models/recorder.py
  spynnaker/pyNN/utilities/constants.py
  spynnaker_integration_tests/test_struct_pl/test_structural_elimination_to_empty.py
  spynnaker_integration_tests/test_struct_pl/test_structural_formation_to_full.py
  unittests/model_tests/neuron/test_neuron_recorder.py
  unittests/test_using_virtual_board/test_set_record.py
Labels: enhancement, incomplete_left_for_further_release
