Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2021-12, with the labels that each got.

#1138 Key translation
  spynnaker/pyNN/spynnaker_external_device_plugin_manager.py
  spynnaker_integration_tests/test_external_devices/test_live_spike_translator.py
Labels: enhancement

#1142 scipy from FEC (which caps)
  requirements.txt
Labels: minor

#1143 Get machine2
  spynnaker_integration_tests/test_various/test_get_machine.py
Labels: enhancement

#1139 Fix Live Voltage Test
  spynnaker_integration_tests/test_external_devices/test_live_neuron_voltage.py
Labels: bug
