Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2021-02, with the labels that each got.

#978 Update defaults
  spynnaker/pyNN/external_devices_models/machine_munich_motor_device.py
  spynnaker/pyNN/external_devices_models/munich_spinnaker_link_motor_device.py
  spynnaker/pyNN/spynnaker.cfg
Labels: enhancement

#942 remove AbstractRecordable as it was never used correctly
  spynnaker/pyNN/models/neuron/population_machine_vertex.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_machine_vertex.py
Labels: bug

#985 FormatAdapter on all loggers
  spynnaker/pyNN/models/populations/population_base.py
  spynnaker/pyNN/models/populations/population_view.py
  spynnaker/pyNN/models/projection.py
  spynnaker8/models/connectors/all_to_all_connector.py
  spynnaker8/models/connectors/array_connector.py
  spynnaker8/models/connectors/csa_connector.py
  spynnaker8/models/connectors/distance_dependent_prob_connector.py
  spynnaker8/models/connectors/fixed_number_post_connector.py
  spynnaker8/models/connectors/fixed_number_pre_connector.py
  spynnaker8/models/connectors/fixed_prob_connector.py
  spynnaker8/models/connectors/from_file_connector.py
  spynnaker8/models/connectors/from_list_connector.py
  spynnaker8/models/connectors/index_based_prob_connector.py
  spynnaker8/models/connectors/kernel_connector_connector.py
  spynnaker8/models/connectors/multapse_connector.py
  spynnaker8/models/connectors/one_to_one_connector.py
  spynnaker8/models/connectors/small_world_connector.py
  spynnaker8/models/populations/assembly.py
  spynnaker8/models/populations/population.py
  spynnaker8/models/populations/population_view.py
  spynnaker8/models/projection.py
  spynnaker8/models/recorder.py
  spynnaker8/models/synapse_dynamics/synapse_dynamics_static.py
  spynnaker8/models/synapse_dynamics/synapse_dynamics_stdp.py
  spynnaker8/models/synapse_dynamics/synapse_dynamics_structural_static.py
  spynnaker8/models/synapse_dynamics/synapse_dynamics_structural_stdp.py
  spynnaker8/models/synapse_dynamics/timing_dependence/timing_dependence_pfister_spike_triplet.py
  spynnaker8/models/synapse_dynamics/timing_dependence/timing_dependence_recurrent.py
  spynnaker8/models/synapse_dynamics/timing_dependence/timing_dependence_spike_nearest_pair.py
  spynnaker8/models/synapse_dynamics/timing_dependence/timing_dependence_spike_pair.py
  spynnaker8/models/synapse_dynamics/timing_dependence/timing_dependence_vogels_2011.py
  spynnaker8/models/synapse_dynamics/weight_dependence/weight_dependence_additive.py
  spynnaker8/models/synapse_dynamics/weight_dependence/weight_dependence_additive_triplet.py
  spynnaker8/models/synapse_dynamics/weight_dependence/weight_dependence_multiplicative.py
Labels: enhancement

#984 Initialize fix
  p8_integration_tests/quick_test/test_change_neuron_parameters_between_runs/test_initialize.py
  p8_integration_tests/quick_test/test_change_neuron_parameters_between_runs/test_set_initial_value.py
  spynnaker/pyNN/models/abstract_models/abstract_population_initializable.py
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/neuron/population_machine_vertex.py
  spynnaker/pyNN/models/populations/idmixin.py
  spynnaker/pyNN/models/populations/population.py
  spynnaker/pyNN/models/populations/population_view.py
  unittests/test_pop_views_assembly/test_idmixin.py
  unittests/test_pop_views_assembly/test_population.py
  unittests/test_pop_views_assembly/test_views.py
  unittests/test_populations/test_population.py
  unittests/test_populations/test_vertex.py
Labels: bug

#986 Host bitfield compressor cleanup (tests)
  p8_integration_tests/quick_test/test_onchip_compressor/test_host_bit_field/spynnaker.cfg
  p8_integration_tests/quick_test/test_onchip_compressor/test_host_bit_field/test_host_bit_field_compressor.py
  p8_integration_tests/quick_test/test_onchip_compressor/test_ordered_covering/spynnaker.cfg
  p8_integration_tests/quick_test/test_onchip_compressor/test_ordered_covering/test_ordered_covering_compressor.py
  p8_integration_tests/quick_test/test_onchip_compressor/test_ordered_covering_bit_field/spynnaker.cfg
  p8_integration_tests/quick_test/test_onchip_compressor/test_ordered_covering_bit_field/test_ordered_covering_bit_field_compressor.py
  p8_integration_tests/quick_test/test_onchip_compressor/test_unordered/spynnaker.cfg
  p8_integration_tests/quick_test/test_onchip_compressor/test_unordered_bit_field/spynnaker.cfg
  spynnaker/pyNN/extra_algorithms/algorithms_metadata.xml
  spynnaker/pyNN/extra_algorithms/spynnaker_machine_bit_field_router_compressor.py
  spynnaker/pyNN/spynnaker.cfg
Labels: enhancement

#823 Add user-defined capability to disallow multapses
  neural_modelling/src/neuron/implementations/neuron_impl_standard.h
  neural_modelling/src/neuron/neuron_recording.c
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis/elimination/elimination_random_by_weight_impl.c
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis/formation/formation_distance_dependent_impl.c
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis/partner_selection/last_neuron_selection_impl.c
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis/sp_structs.h
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis/topographic_map_impl.c
  p8_integration_tests/quick_test/test_struct_pl/test_structural_formation_to_full.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/abstract_synapse_dynamics_structural.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_static.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_stdp.py
Labels: enhancement

#987 fix write_bit_field_compressor_report
  spynnaker/pyNN/spynnaker.cfg
Labels: BLOCKER!, bug

#951 Use new transceiver API for reading a single word
  spynnaker/pyNN/extra_algorithms/on_chip_bit_field_generator.py
  spynnaker/pyNN/models/common/eieio_spike_recorder.py
  spynnaker/pyNN/models/common/recording_utils.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_machine_vertex.py
  unittests/model_tests/neuron/test_synaptic_manager.py
Labels: enhancement, minor

#989 Put doc builds in parallel with other validation
  .github/workflows/python_actions.yml
Labels: enhancement, minor

#990 dont mix nparray and empty list
  p8_integration_tests/quick_test/test_multi_call_examples/test_reset_initialize.py
  p8_integration_tests/quick_test/test_spike_source/test_spike_source_array.py
  spynnaker/pyNN/extra_algorithms/splitter_components/splitter_abstract_pop_vertex_slice.py
  spynnaker/pyNN/models/populations/population.py
  spynnaker/pyNN/models/spike_source/spike_source_array_vertex.py
Labels: BLOCKER!, bug

#993 Recorder cleanup
  spynnaker/pyNN/models/populations/population.py
  spynnaker/pyNN/models/populations/population_view.py
  spynnaker/pyNN/models/recorder.py
  unittests/test_pop_views_assembly/test_record.py
  unittests/test_using_virtual_board/test_set_record.py
Labels: enhancement

#996 Adds back test removed in 990
  p8_integration_tests/quick_test/test_spike_source/test_spike_source_array.py
Labels: enhancement, minor

#994 Dont inherit from pynn
  spynnaker/pyNN/models/neural_projections/connectors/all_to_all_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/distance_dependent_probability_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_number_post_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_number_pre_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_probability_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/from_file_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/one_to_one_connector.py
Labels: enhancement

#997 use moved_in_v6
  spynnaker8/models/connectors/all_to_all_connector.py
  spynnaker8/models/connectors/array_connector.py
  spynnaker8/models/connectors/csa_connector.py
  spynnaker8/models/connectors/distance_dependent_prob_connector.py
  spynnaker8/models/connectors/fixed_number_post_connector.py
  spynnaker8/models/connectors/fixed_number_pre_connector.py
  spynnaker8/models/connectors/fixed_prob_connector.py
  spynnaker8/models/connectors/from_file_connector.py
  spynnaker8/models/connectors/from_list_connector.py
  spynnaker8/models/connectors/index_based_prob_connector.py
  spynnaker8/models/connectors/kernel_connector_connector.py
  spynnaker8/models/connectors/multapse_connector.py
  spynnaker8/models/connectors/one_to_one_connector.py
  spynnaker8/models/connectors/small_world_connector.py
  spynnaker8/models/populations/assembly.py
  spynnaker8/models/populations/population.py
  spynnaker8/models/populations/population_view.py
  spynnaker8/models/projection.py
  spynnaker8/models/recorder.py
  spynnaker8/models/synapse_dynamics/synapse_dynamics_static.py
  spynnaker8/models/synapse_dynamics/synapse_dynamics_stdp.py
  spynnaker8/models/synapse_dynamics/synapse_dynamics_structural_static.py
  spynnaker8/models/synapse_dynamics/synapse_dynamics_structural_stdp.py
  spynnaker8/models/synapse_dynamics/timing_dependence/timing_dependence_pfister_spike_triplet.py
  spynnaker8/models/synapse_dynamics/timing_dependence/timing_dependence_recurrent.py
  spynnaker8/models/synapse_dynamics/timing_dependence/timing_dependence_spike_nearest_pair.py
  spynnaker8/models/synapse_dynamics/timing_dependence/timing_dependence_spike_pair.py
  spynnaker8/models/synapse_dynamics/timing_dependence/timing_dependence_vogels_2011.py
  spynnaker8/models/synapse_dynamics/weight_dependence/weight_dependence_additive.py
  spynnaker8/models/synapse_dynamics/weight_dependence/weight_dependence_additive_triplet.py
  spynnaker8/models/synapse_dynamics/weight_dependence/weight_dependence_multiplicative.py
Labels: enhancement, minor

#1001 Allow Neo9
  requirements.txt
  setup.py
Labels: minor

#1003 Restore doing the (very slow!) doc builds in parallel with testing
  .github/workflows/python_actions.yml
Labels: enhancement

#1002 added 3.9 and rat 3.8 (more like other repr)
  .github/workflows/c_actions.yml
  .github/workflows/publish.yml
  .github/workflows/python_actions.yml
  doc/source/conf.py
  setup.py
Labels: enhancement, minor

#1011 We need to use today's new special matplotlib trickery
  .github/workflows/publish.yml
  .github/workflows/python_actions.yml
Labels: BLOCKER!, bug

#1010 Much faster documentation building
  .github/workflows/python_actions.yml
  doc/source/conf.py
Labels: EVIL VANQUISHED, bug

#1013 cap matplotlib and remove duplicate quantites
  requirements.txt
Labels: minor

#1006 remove unnecessary references from neural_build.mk
  neural_modelling/makefiles/neuron/neural_build.mk
  neural_modelling/src/neuron/implementations/neuron_impl_external_devices.h
  neural_modelling/src/neuron/implementations/neuron_impl_standard.h
  neural_modelling/src/neuron/synapse_types/synapse_types.h
  neural_modelling/src/neuron/synapse_types/synapse_types_alpha_impl.h
  neural_modelling/src/neuron/synapse_types/synapse_types_delta_impl.h
  neural_modelling/src/neuron/synapse_types/synapse_types_dual_excitatory_exponential_impl.h
  neural_modelling/src/neuron/synapse_types/synapse_types_exponential_impl.h
  neural_modelling/src/neuron/synapse_types/synapse_types_semd_impl.h
Labels: bug

#1015 Deal with cases with mixed list and RandomDistribution, add tests
  p8_integration_tests/quick_test/test_connectors/test_from_list_connector_mixed.py
  spynnaker/pyNN/models/neural_projections/connectors/from_list_connector.py
Labels: bug

#1005 Lost spike issues
  neural_modelling/src/delay_extension/delay_extension.c
  neural_modelling/src/delay_extension/delay_extension.h
  neural_modelling/src/neuron/c_main.c
  neural_modelling/src/neuron/implementations/neuron_impl_external_devices.h
  neural_modelling/src/neuron/population_table/population_table_binary_search_impl.c
  neural_modelling/src/neuron/spike_processing.c
  neural_modelling/src/neuron/synapses.c
  neural_modelling/src/spike_source/poisson/spike_source_poisson.c
  p8_integration_tests/quick_test/test_auto_pause_and_resume_tests/test_long_run/spynnaker.cfg
  p8_integration_tests/quick_test/test_auto_pause_and_resume_tests/test_medium_run/spynnaker.cfg
  spynnaker/pyNN/models/neuron/population_machine_vertex.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_machine_vertex.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py
Labels: bug, enhancement

#1016 More exposed via global variables
  p8_integration_tests/base_test_case.py
  p8_integration_tests/quick_test/test_iobuf/test_iobuf_without_during_run_flag/test_noIobuf_during_run.py
  p8_integration_tests/quick_test/test_iobuf/test_multirun/test_multirun_with.py
  p8_integration_tests/quick_test/test_iobuf/test_none_but_active_recorded/test_no_cores.py
  spynnaker/pyNN/utilities/spynnaker_failed_state.py
Labels: enhancement

#1019 These globals are no longer used in this impl
  neural_modelling/src/neuron/implementations/neuron_impl_external_devices.h
Labels: bug, minor
