Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2021-03, with the labels that each got.

#1022 Config2
  spynnaker/pyNN/abstract_spinnaker_common.py
  spynnaker/pyNN/utilities/spynnaker_failed_state.py
Labels: enhancement

#1024 Less virtual
  .github/workflows/python_actions.yml
  .ratexcludes
  unittests/test_integration_using_virtual_board/test_synfire_6300n_10pop_10pc_48chips_with_no_delays_spike_recording.py
  unittests/test_integration_using_virtual_board/test_synfire_posson_if_curr_exp_parameter_test_second_none.py
  unittests/test_using_virtual_board/test_examples.py
  unittests/test_using_virtual_board/test_introlabs.py
  unittests/test_using_virtual_board/test_radial_placer/test_synfire_200n_10pc_2chips_with_no_delays_spike_recording.py
Labels: EVIL VANQUISHED

#1021 Proveance reader
  p8_integration_tests/long_test/test_many_boards/test_java_advanced/test_java_advanced.py
  p8_integration_tests/long_test/test_many_boards/test_java_simple/test_java_simple.py
  p8_integration_tests/long_test/test_many_boards/test_python_advanced/test_python_advanced.py
  p8_integration_tests/long_test/test_many_boards/test_python_simple/test_python_simple.py
  p8_integration_tests/quick_test/test_debug_mode/check_debug.py
  p8_integration_tests/quick_test/test_many_boards/test_java_advanced/test_java_advanced.py
  p8_integration_tests/quick_test/test_many_boards/test_java_simple/test_java_simple.py
  p8_integration_tests/quick_test/test_many_boards/test_python_advanced/test_python_advanced.py
  p8_integration_tests/quick_test/test_many_boards/test_python_simple/test_python_simple.py
  p8_integration_tests/quick_test/test_struct_pl/test_structural_elimination_to_empty.py
Labels: enhancement

#1020 Split out the list of files to put in documentation
  doc/source/conf.py
  doc/unfiltered-files.txt
Labels: enhancement, minor

#1025 Remove a bad link
  doc/source/index.rst
Labels: bug, minor

#1031 No need for current_file_path as BaseTestCase cd into it
  p8_integration_tests/quick_test/test_param_vertex_retrieval_from_board_after_1_run/test_synfire_200n_100pc_with_delays_all_recording.py
  p8_integration_tests/quick_test/test_param_vertex_retrieval_from_board_after_1_run/test_synfire_20n_20pc_delays_delay_extensions_all_recording.py
  p8_integration_tests/quick_test/test_param_vertex_retrieval_from_board_after_1_run/test_synfire_20n_20pc_delays_no_delay_extension_all_recording.py
  p8_integration_tests/quick_test/test_param_vertex_retrieval_from_board_after_1_run/test_synfire_20n_20pc_no_delays_all_recording.py
  p8_integration_tests/quick_test/test_selective_recording/test_recording_on_off.py
Labels: enhancement

#1032 Simplify recording
  neural_modelling/src/neuron/neuron_recording.h
  neural_modelling/src/spike_source/poisson/spike_source_poisson.c
  spynnaker/pyNN/models/common/neuron_recorder.py
Labels: enhancement

#974 Allow distance-dependent weights and delays
  spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/abstract_generate_connector_on_machine.py
  spynnaker/pyNN/models/neural_projections/connectors/all_to_all_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/array_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/csa_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/distance_dependent_probability_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_number_post_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_number_pre_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_probability_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/from_list_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/index_based_probability_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/kernel_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/multapse_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/one_to_one_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/small_world_connector.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/abstract_synapse_dynamics.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_static.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  spynnaker/pyNN/models/projection.py
  spynnaker_integration_tests/test_grid_based_connectors/test_distance_dependent_weights_and_delays.py
Labels: enhancement

#1043 Use right token for coveralls
  .github/workflows/python_actions.yml
Labels: BLOCKER!, bug, minor

#1046 recover and fix FromFile test
  spynnaker_integration_tests/test_various/test_from_file_connector_large.py
Labels: enhancement

#1049 Clear cache
  spynnaker/pyNN/abstract_spinnaker_common.py
  spynnaker/pyNN/models/neuron/synaptic_matrix_app.py
Labels: BLOCKER!, bug

#1050 Small doc fixes
  spynnaker/pyNN/models/neuron/synapse_dynamics/abstract_synapse_dynamics_structural.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_static.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_stdp.py
Labels: enhancement
