Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2021-04, with the labels that each got.

#1054 Move Development Status to setup.py
  setup.py
  spynnaker/_version.py
Labels: enhancement

#1055 Spinnaker testbase
  requirements-test.txt
Labels: bug

#1057 Update publish.yml
  .github/workflows/publish.yml
Labels: blocker, bug

#1058 Bump6.0.1
  doc/source/conf.py
  requirements-test.txt
  requirements.txt
  setup.py
  spynnaker/_version.py
  spynnaker/pyNN/_version.py
Labels: next_release

#1065 Config checker
  spynnaker/pyNN/spynnaker.cfg
  unittests/test_cfg_checker.py
Labels: enhancement

#1066 Add test for output of record("packets-per-timestep")
  spynnaker_integration_tests/test_various/test_record_packets_per_timestep.py
Labels: enhancement, minor

#1067 Cfg stack
  spynnaker/pyNN/abstract_spinnaker_common.py
  spynnaker/pyNN/config_setup.py
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/neuron/synaptic_manager.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py
  spynnaker/pyNN/spynnaker.cfg
  spynnaker/pyNN/spynnaker_external_device_plugin_manager.py
  spynnaker_integration_tests/test_big_connection/test_big_connection.py
  spynnaker_integration_tests/test_debug_mode/check_debug.py
  spynnaker_integration_tests/test_many_boards/many_boards.py
  unittests/model_tests/neuron/test_synaptic_manager.py
  unittests/test_cfg_checker.py
Labels: enhancement
