Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2021-06, with the labels that each got.

#1087 use svg for big files in SpYNNakerNeuronGraphNetworkSpecificationReport
  spynnaker/pyNN/extra_algorithms/spynnaker_neuron_network_specification_report.py
  spynnaker/pyNN/spynnaker.cfg
  unittests/test_using_virtual_board/test_debug_mode/spynnaker.cfg
  unittests/test_using_virtual_board/test_debug_mode/test_debug.py
Labels: enhancement

#1086 Test objects
  unittests/connector_tests/test_csa_connector.py
  unittests/connector_tests/test_from_list_connector.py
  unittests/mocks.py
  unittests/model_tests/neuron/test_synaptic_manager.py
  unittests/model_tests/test_connectors.py
  unittests/test_from_file_connector.py
Labels: enhancement

#1088 remove tests of already removed functionality
  spynnaker_integration_tests/test_energy_params_validity/__init__.py
  spynnaker_integration_tests/test_energy_params_validity/test_power_saving_turned_on_after_discovery/__init__.py
  spynnaker_integration_tests/test_energy_params_validity/test_power_saving_turned_on_after_discovery/spynnaker.cfg
  spynnaker_integration_tests/test_energy_params_validity/test_power_saving_turned_on_after_discovery/test_power_savings.py
  spynnaker_integration_tests/test_energy_params_validity/test_power_savings_turned_off/__init__.py
  spynnaker_integration_tests/test_energy_params_validity/test_power_savings_turned_off/spynnaker.cfg
  spynnaker_integration_tests/test_energy_params_validity/test_power_savings_turned_off/test_no_power_savings.py
Labels: blocker

#1071 Fix issue with master pop in some cases
  spynnaker/pyNN/models/neuron/synaptic_matrices.py
  unittests/model_tests/neuron/test_synaptic_manager.py
Labels: bug

#1091 Return false after logging error
  neural_modelling/src/neuron/synapses.c
Labels: bug

#1089 report directories as global_variables
  spynnaker/pyNN/extra_algorithms/algorithms_metadata.xml
  spynnaker/pyNN/extra_algorithms/on_chip_bit_field_generator.py
  spynnaker/pyNN/extra_algorithms/redundant_packet_count_report.py
  spynnaker/pyNN/extra_algorithms/spynnaker_data_specification_writer.py
  spynnaker/pyNN/extra_algorithms/spynnaker_machine_bit_field_router_compressor.py
  spynnaker/pyNN/extra_algorithms/spynnaker_neuron_network_specification_report.py
  spynnaker/pyNN/extra_algorithms/spynnaker_synaptic_matrix_report.py
  spynnaker/pyNN/extra_algorithms/synapse_expander.py
  spynnaker_integration_tests/scripts/synfire_runner.py
  spynnaker_integration_tests/test_debug_mode/check_debug.py
  spynnaker_integration_tests/test_power_monitoring/test_power_mon.py
  spynnaker_integration_tests/test_struct_pl/test_structural_elimination_to_empty.py
  unittests/test_using_virtual_board/test_debug_mode/test_debug.py
Labels: enhancement

#1097 Remove functions that aren't implemented so don't return anything
  spynnaker/pyNN/models/projection.py
Labels: bug
