Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2021-01, with the labels that each got.

#957 upgrade neo
  requirements.txt
Labels: BLOCKER!, bug

#959 Make scaling_factor into a model parameter for sEMD
  neural_modelling/src/neuron/synapse_types/synapse_types_semd_impl.h
  spynnaker/pyNN/models/neuron/builds/if_curr_exp_semd_base.py
  spynnaker/pyNN/models/neuron/synapse_types/synapse_type_semd.py
Labels: enhancement

#955 log warning to file
  spynnaker/pyNN/connections/ethernet_control_connection.py
  spynnaker/pyNN/external_devices_models/external_device_lif_control.py
  spynnaker/pyNN/external_devices_models/external_device_lif_control_vertex.py
  spynnaker/pyNN/external_devices_models/external_spinnaker_link_fpga_retina_device.py
  spynnaker/pyNN/external_devices_models/munich_spinnaker_link_motor_device.py
  spynnaker/pyNN/external_devices_models/push_bot/push_bot_control_modules/push_bot_lif_spinnaker_link.py
  spynnaker/pyNN/external_devices_models/push_bot/push_bot_ethernet/push_bot_retina_connection.py
  spynnaker/pyNN/external_devices_models/push_bot/push_bot_ethernet/push_bot_wifi_connection.py
  spynnaker/pyNN/external_devices_models/push_bot/push_bot_spinnaker_link/push_bot_spinnaker_link_retina_device.py
  spynnaker/pyNN/extra_algorithms/graph_edge_weight_updater.py
  spynnaker/pyNN/extra_algorithms/spynnaker_connection_holder_generations.py
  spynnaker/pyNN/extra_algorithms/spynnaker_machine_bit_field_router_compressor.py
  spynnaker/pyNN/extra_algorithms/spynnaker_neuron_network_specification_report.py
  spynnaker/pyNN/extra_algorithms/spynnaker_synaptic_matrix_report.py
  spynnaker/pyNN/extra_algorithms/synapse_expander.py
  spynnaker/pyNN/models/common/recording_utils.py
  spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/array_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/csa_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/distance_dependent_probability_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/from_list_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/index_based_probability_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/multapse_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/one_to_one_connector.py
  spynnaker/pyNN/models/neural_projections/projection_application_edge.py
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/neuron/master_pop_table.py
  spynnaker/pyNN/models/neuron/plasticity/stdp/common.py
  spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/timing_dependence_pfister_spike_triplet.py
  spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/timing_dependence_spike_nearest_pair.py
  spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/timing_dependence_spike_pair.py
  spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/timing_dependence_vogels_2011.py
  spynnaker/pyNN/models/pynn_projection_common.py
  spynnaker/pyNN/models/spike_source/spike_source_array_vertex.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py
  spynnaker/pyNN/models/utility_models/spike_injector/spike_injector_vertex.py
  spynnaker/pyNN/protocols/munich_io_spinnaker_link_protocol.py
  spynnaker/pyNN/utilities/utility_calls.py
Labels: enhancement

#960 Warn if user supplies spike time for SSA that's too low
  spynnaker/pyNN/models/spike_source/spike_source_array_vertex.py
Labels: enhancement

#961 input_type is not always const in this function (see example in NMT)
  neural_modelling/src/neuron/input_types/input_type.h
  neural_modelling/src/neuron/input_types/input_type_conductance.h
  neural_modelling/src/neuron/input_types/input_type_current.h
  neural_modelling/src/neuron/input_types/input_type_delta.h
  neural_modelling/src/neuron/input_types/input_type_none.h
Labels: bug, minor

#964 Remove unused OVERSCALE multipliers
  spynnaker/pyNN/models/neuron/master_pop_table.py
  spynnaker/pyNN/models/neuron/synaptic_matrices.py
Labels: bug, minor

#935 Validate mars kiss seeds before use
  spynnaker/pyNN/models/neural_projections/connectors/abstract_generate_connector_on_machine.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_number_post_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/fixed_number_pre_connector.py
  spynnaker/pyNN/utilities/utility_calls.py
Labels: bug

#963 remove MundyOnChipRouterCompression in commented out reference
  spynnaker/pyNN/spynnaker.cfg
Labels: enhancement, minor

#968 Stop relying on the compiler being clever
  neural_modelling/src/neuron/implementations/neuron_impl_standard.h
Labels: bug

#970 Replace %s with {} when using formatadapter during logging
  spynnaker/pyNN/extra_algorithms/spynnaker_synaptic_matrix_report.py
Labels: bug, minor

#972 unmutable models
  spynnaker/pyNN/models/neuron/additional_inputs/additional_input_ca2_adaptive.py
  spynnaker/pyNN/models/neuron/builds/if_cond_exp_base.py
  spynnaker/pyNN/models/neuron/builds/if_cond_exp_stoc.py
  spynnaker/pyNN/models/neuron/builds/if_curr_alpha.py
  spynnaker/pyNN/models/neuron/builds/if_curr_delta.py
  spynnaker/pyNN/models/neuron/builds/if_curr_dual_exp_base.py
  spynnaker/pyNN/models/neuron/builds/if_curr_exp_base.py
  spynnaker/pyNN/models/neuron/builds/if_curr_exp_ca2_adaptive.py
  spynnaker/pyNN/models/neuron/builds/if_curr_exp_semd_base.py
  spynnaker/pyNN/models/neuron/builds/izk_cond_exp_base.py
  spynnaker/pyNN/models/neuron/builds/izk_curr_exp_base.py
  spynnaker/pyNN/models/neuron/implementations/abstract_standard_neuron_component.py
  spynnaker/pyNN/models/neuron/implementations/neuron_impl_standard.py
  spynnaker/pyNN/models/neuron/input_types/input_type_conductance.py
  spynnaker/pyNN/models/neuron/input_types/input_type_current_semd.py
  spynnaker/pyNN/models/neuron/neuron_models/neuron_model_izh.py
  spynnaker/pyNN/models/neuron/neuron_models/neuron_model_leaky_integrate_and_fire.py
  spynnaker/pyNN/models/neuron/synapse_types/synapse_type_alpha.py
  spynnaker/pyNN/models/neuron/synapse_types/synapse_type_delta.py
  spynnaker/pyNN/models/neuron/synapse_types/synapse_type_dual_exponential.py
  spynnaker/pyNN/models/neuron/synapse_types/synapse_type_exponential.py
  spynnaker/pyNN/models/neuron/synapse_types/synapse_type_semd.py
  spynnaker/pyNN/models/neuron/threshold_types/threshold_type_maass_stochastic.py
  spynnaker/pyNN/models/neuron/threshold_types/threshold_type_static.py
Labels: bug, enhancement
