Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2022-05, with the labels that each got.

#1173 Remove unused code
  spynnaker/pyNN/models/common/__init__.py
  spynnaker/pyNN/models/common/recording_utils.py
Labels: minor

#1174 remove spynnaker8 references
  setup.py
  spynnaker_integration_tests/scripts/synfire_runner.py
  spynnaker_integration_tests/test_external_devices/test_live_sync.py
  spynnaker_integration_tests/test_various/test_synaptic_expander.py
  unittests/test_cfg_checker.py
Labels: minor

#1151 Whole board test
  spynnaker/pyNN/extra_algorithms/on_chip_bit_field_generator.py
  spynnaker/pyNN/extra_algorithms/synapse_expander.py
  spynnaker/pyNN/models/abstract_models/abstract_synapse_expandable.py
  spynnaker/pyNN/models/neuron/population_machine_synapses.py
  spynnaker/pyNN/models/neuron/synaptic_matrices.py
  spynnaker/pyNN/models/neuron/synaptic_matrix_app.py
  test_whole_board/test_whole_board.py
Labels: enhancement

#1179 spinnaker_get_data
  spynnaker/pyNN/models/populations/population.py
  spynnaker/pyNN/models/populations/population_view.py
  spynnaker/pyNN/models/recorder.py
  spynnaker_integration_tests/test_views/test_views.py
  spynnaker_integration_tests/test_views/test_views_data.py
Labels: enhancement

#1076 Current sources
  neural_modelling/makefiles/neuron/IF_cond_exp_stdp_izhikevich_neuromodulation_pair_additive/Makefile
  neural_modelling/makefiles/neuron/IF_cond_exp_stdp_izhikevich_neuromodulation_pair_multiplicative/Makefile
  neural_modelling/makefiles/neuron/IF_cond_exp_stdp_mad_nearest_pair_additive_structural_last_neuron_distance_weight/Makefile
  neural_modelling/makefiles/neuron/IF_cond_exp_stdp_mad_nearest_pair_additive_structural_random_distance_weight/Makefile
  neural_modelling/makefiles/neuron/IF_cond_exp_stdp_mad_pair_additive_structural_last_neuron_distance_weight/Makefile
  neural_modelling/makefiles/neuron/IF_cond_exp_stdp_mad_pair_additive_structural_random_distance_weight/Makefile
  neural_modelling/makefiles/neuron/IF_curr_exp_stdp_izhikevich_neuromodulation_pair_additive/Makefile
  neural_modelling/makefiles/neuron/IF_curr_exp_stdp_izhikevich_neuromodulation_pair_multiplicative/Makefile
  neural_modelling/makefiles/neuron/IF_curr_exp_stdp_izhikevich_neuromodulation_vogels_2011_additive/Makefile
  neural_modelling/makefiles/neuron/IF_curr_exp_stdp_mad_pair_additive_structural_last_neuron_distance_weight/Makefile
  neural_modelling/makefiles/neuron/IF_curr_exp_stdp_mad_pair_additive_structural_random_distance_weight/Makefile
  neural_modelling/makefiles/neuron/IZK_cond_exp_stdp_izhikevich_neuromodulation_pair_additive/Makefile
  neural_modelling/makefiles/neuron/IZK_cond_exp_stdp_izhikevich_neuromodulation_pair_multiplicative/Makefile
  neural_modelling/makefiles/neuron/IZK_curr_exp_stdp_izhikevich_neuromodulation_pair_additive/Makefile
  neural_modelling/makefiles/neuron/IZK_curr_exp_stdp_izhikevich_neuromodulation_pair_multiplicative/Makefile
  neural_modelling/makefiles/neuron/neural_build.mk
  neural_modelling/makefiles/neuron_only/neuron_build.mk
  neural_modelling/src/neuron/c_main.c
  neural_modelling/src/neuron/c_main_neuron_common.h
  neural_modelling/src/neuron/c_main_neurons.c
  neural_modelling/src/neuron/current_sources/current_source.h
  neural_modelling/src/neuron/current_sources/current_source_ac.h
  neural_modelling/src/neuron/current_sources/current_source_ac_only_impl.h
  neural_modelling/src/neuron/current_sources/current_source_dc.h
  neural_modelling/src/neuron/current_sources/current_source_dc_only_impl.h
  neural_modelling/src/neuron/current_sources/current_source_impl.h
  neural_modelling/src/neuron/current_sources/current_source_noisy.h
  neural_modelling/src/neuron/current_sources/current_source_noisy_only_impl.h
  neural_modelling/src/neuron/current_sources/current_source_step.h
  neural_modelling/src/neuron/current_sources/current_source_step_only_impl.h
  neural_modelling/src/neuron/current_sources/current_source_stepnoisy_impl.h
  neural_modelling/src/neuron/implementations/neuron_impl_external_devices.h
  neural_modelling/src/neuron/implementations/neuron_impl_standard.h
  neural_modelling/src/neuron/models/neuron_model.h
  neural_modelling/src/neuron/models/neuron_model_izh_impl.h
  neural_modelling/src/neuron/models/neuron_model_lif_impl.h
  neural_modelling/src/neuron/neuron.c
  neural_modelling/src/neuron/neuron.h
  neural_modelling/src/neuron/regions.h
  spynnaker/pyNN/__init__.py
  spynnaker/pyNN/models/current_sources/__init__.py
  spynnaker/pyNN/models/current_sources/abstract_current_source.py
  spynnaker/pyNN/models/current_sources/ac_source.py
  spynnaker/pyNN/models/current_sources/dc_source.py
  spynnaker/pyNN/models/current_sources/noisy_current_source.py
  spynnaker/pyNN/models/current_sources/step_current_source.py
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/neuron/population_machine_neurons.py
  spynnaker/pyNN/models/neuron/population_machine_vertex.py
  spynnaker/pyNN/models/neuron/population_neurons_machine_vertex.py
  spynnaker/pyNN/models/populations/idmixin.py
  spynnaker/pyNN/models/populations/population.py
  spynnaker/pyNN/models/populations/population_base.py
  spynnaker/pyNN/models/populations/population_view.py
  spynnaker8/__init__.py
Labels: enhancement

#1171 Put projection._clear_cache back
  spynnaker/pyNN/spinnaker.py
Labels: bug, question
