Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2022-08, with the labels that each got.

#1204 Assert bracket fix
  spynnaker/pyNN/models/neural_projections/connectors/fixed_probability_connector.py
  spynnaker_integration_tests/test_auto_pause_and_resume_tests/test_run_forever_recorded/test_run_forever_recorded.py
  spynnaker_integration_tests/test_connectors/test_fixed_number_pre_connector.py
  spynnaker_integration_tests/test_external_devices/test_live_neuron_voltage.py
  spynnaker_integration_tests/test_external_devices/test_live_sync.py
  spynnaker_integration_tests/test_multi_call_examples/test_stdp_random_run.py
  spynnaker_integration_tests/test_projection_param_retrieval_from_board/test_large_pop_weight_delay_retrieval.py
  spynnaker_integration_tests/test_spike_source/test_variable_rate.py
  spynnaker_integration_tests/test_split_various/test_split_delays.py
  spynnaker_integration_tests/test_split_various/test_split_simple.py
  spynnaker_integration_tests/test_split_various/test_split_stdp.py
  spynnaker_integration_tests/test_split_various/test_split_struct.py
  spynnaker_integration_tests/test_split_various/test_split_struct_stdp.py
  spynnaker_integration_tests/test_stdp/test_STDP_pair_additive.py
  spynnaker_integration_tests/test_stdp/test_STDP_pair_multiplicative.py
  spynnaker_integration_tests/test_stdp/test_STDP_record_weights.py
  spynnaker_integration_tests/test_struct_pl/test_structural_elimination_to_empty.py
  spynnaker_integration_tests/test_struct_pl/test_structural_shared.py
  spynnaker_integration_tests/test_struct_pl/test_structural_with_stdp.py
  spynnaker_integration_tests/test_struct_pl/test_structural_without_stdp.py
  spynnaker_integration_tests/test_various/test_record_packets_per_timestep.py
  spynnaker_integration_tests/test_various/test_synaptic_expander.py
  spynnaker_integration_tests/test_views/test_views.py
  unittests/connector_tests/test_csa_connector.py
  unittests/connector_tests/test_from_list_connector.py
  unittests/model_tests/neuron/test_abstract_neuron_impl.py
  unittests/model_tests/neuron/test_defaults.py
  unittests/model_tests/neuron/test_neuron_recorder.py
  unittests/model_tests/neuron/test_synaptic_manager.py
  unittests/model_tests/test_connectors.py
  unittests/test_from_file_connector.py
  unittests/test_integration_using_virtual_board/test_one_pop_lif_example.py
  unittests/test_pop_views_assembly/test_idmixin.py
  unittests/test_using_virtual_board/test_from_file_connector.py
  unittests/test_using_virtual_board/test_from_list_connector.py
Labels: blocker

#1206 hide Placements
  spynnaker/pyNN/spinnaker.py
  spynnaker_integration_tests/test_iobuf/test_cores_and_binaries_recorded/test_cores_and_binaries_recording.py
  spynnaker_integration_tests/test_iobuf/test_multirun/test_multirun_with.py
  spynnaker_integration_tests/test_iobuf/test_only_binaries_recorded/test_only_binaries_recording.py
Labels: enhancement

#1205 remove unused resources
  spynnaker/pyNN/external_devices_models/machine_munich_motor_device.py
  spynnaker/pyNN/external_devices_models/threshold_type_multicast_device_control.py
  spynnaker/pyNN/extra_algorithms/splitter_components/splitter_abstract_pop_vertex_fixed.py
  spynnaker/pyNN/extra_algorithms/splitter_components/splitter_abstract_pop_vertex_neurons_synapses.py
  spynnaker/pyNN/extra_algorithms/splitter_components/splitter_delay_vertex_slice.py
  spynnaker/pyNN/models/common/eieio_spike_recorder.py
  spynnaker/pyNN/models/common/multi_spike_recorder.py
  spynnaker/pyNN/models/common/neuron_recorder.py
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/neuron/additional_inputs/additional_input_ca2_adaptive.py
  spynnaker/pyNN/models/neuron/implementations/abstract_neuron_impl.py
  spynnaker/pyNN/models/neuron/implementations/abstract_standard_neuron_component.py
  spynnaker/pyNN/models/neuron/implementations/neuron_impl_standard.py
  spynnaker/pyNN/models/neuron/input_types/input_type_conductance.py
  spynnaker/pyNN/models/neuron/input_types/input_type_current.py
  spynnaker/pyNN/models/neuron/input_types/input_type_current_semd.py
  spynnaker/pyNN/models/neuron/input_types/input_type_delta.py
  spynnaker/pyNN/models/neuron/neuron_models/abstract_neuron_model.py
  spynnaker/pyNN/models/neuron/neuron_models/neuron_model_izh.py
  spynnaker/pyNN/models/neuron/neuron_models/neuron_model_leaky_integrate_and_fire.py
  spynnaker/pyNN/models/neuron/population_machine_common.py
  spynnaker/pyNN/models/neuron/population_machine_vertex.py
  spynnaker/pyNN/models/neuron/population_neurons_machine_vertex.py
  spynnaker/pyNN/models/neuron/population_synapses_machine_vertex_common.py
  spynnaker/pyNN/models/neuron/population_synapses_machine_vertex_lead.py
  spynnaker/pyNN/models/neuron/population_synapses_machine_vertex_shared.py
  spynnaker/pyNN/models/neuron/synapse_types/synapse_type_alpha.py
  spynnaker/pyNN/models/neuron/synapse_types/synapse_type_delta.py
  spynnaker/pyNN/models/neuron/synapse_types/synapse_type_dual_exponential.py
  spynnaker/pyNN/models/neuron/synapse_types/synapse_type_exponential.py
  spynnaker/pyNN/models/neuron/synapse_types/synapse_type_izhikevich_neuromodulated.py
  spynnaker/pyNN/models/neuron/synapse_types/synapse_type_semd.py
  spynnaker/pyNN/models/neuron/threshold_types/threshold_type_maass_stochastic.py
  spynnaker/pyNN/models/neuron/threshold_types/threshold_type_static.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_machine_vertex.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_machine_vertex.py
  unittests/test_populations/test_vertex.py
Labels: enhancement

#1210 Delete a duplicate test
  unittests/utilities_tests/test_spinnaker_main_interface.py
Labels: bug, minor

#1176 Use SpiNNMan more
  spynnaker/pyNN/external_devices_models/push_bot/ethernet/push_bot_wifi_connection.py
  spynnaker/pyNN/external_devices_models/push_bot/parameters/push_bot_retina_viewer.py
Labels: enhancement, minor

#1214 Fix version of matplotlib for python 3.7
  requirements.txt
Labels: bug

#1215 Matplotlib cap
  requirements.txt
  setup.py
Labels: blocker
