Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2022-09, with the labels that each got.

#1208 remove globals_variables
  spynnaker/pyNN/__init__.py
  spynnaker/pyNN/config_setup.py
  spynnaker/pyNN/data/spynnaker_data_view.py
  spynnaker/pyNN/external_devices/__init__.py
  spynnaker/pyNN/models/populations/assembly.py
  spynnaker/pyNN/models/recorder.py
  unittests/data/test_simulator_data.py
  unittests/test_using_virtual_board/test_failed_state.py
Labels: enhancement

#1217 View holds requires
  spynnaker/pyNN/extra_algorithms/delay_support_adder.py
  spynnaker/pyNN/models/current_sources/step_current_source.py
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_static.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py
  spynnaker/pyNN/models/populations/idmixin.py
  spynnaker/pyNN/models/populations/population.py
  spynnaker/pyNN/models/populations/population_view.py
  spynnaker/pyNN/models/projection.py
  spynnaker/pyNN/models/spike_source/spike_source_array_vertex.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
  spynnaker/pyNN/spinnaker.py
  spynnaker_integration_tests/test_various/test_get_machine.py
  spynnaker_integration_tests/test_various/test_long_delay.py
  spynnaker_integration_tests/test_various/test_multi_delay.py
  unittests/model_tests/neuron/test_synaptic_manager.py
  unittests/utilities_tests/recorder.sqlite3
Labels: enhancement

#1103 Tidy up debug code
  .github/workflows/c_actions.yml
  neural_modelling/makefiles/neuron/Makefile
  neural_modelling/makefiles/synapse_only/Makefile
  neural_modelling/src/neuron/c_main.c
  neural_modelling/src/neuron/c_main_common.h
  neural_modelling/src/neuron/c_main_neurons.c
  neural_modelling/src/neuron/c_main_synapses.c
  neural_modelling/src/neuron/implementations/neuron_impl.h
  neural_modelling/src/neuron/implementations/neuron_impl_external_devices.h
  neural_modelling/src/neuron/implementations/neuron_impl_standard.h
  neural_modelling/src/neuron/neuron.c
  neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_common.h
  neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_izhikevich_neuromodulation.c
  neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_mad_impl.c
  neural_modelling/src/neuron/plasticity/stdp/timing_dependence/timing_nearest_pair_impl.h
  neural_modelling/src/neuron/plasticity/stdp/timing_dependence/timing_pair_impl.c
  neural_modelling/src/neuron/plasticity/stdp/timing_dependence/timing_pfister_triplet_impl.c
  neural_modelling/src/neuron/plasticity/stdp/timing_dependence/timing_recurrent_common.h
  neural_modelling/src/neuron/plasticity/stdp/timing_dependence/timing_recurrent_pre_stochastic_impl.c
  neural_modelling/src/neuron/plasticity/stdp/weight_dependence/weight_additive_one_term_impl.c
  neural_modelling/src/neuron/plasticity/stdp/weight_dependence/weight_additive_two_term_impl.c
  neural_modelling/src/neuron/plasticity/stdp/weight_dependence/weight_multiplicative_impl.c
  neural_modelling/src/neuron/population_table/population_table_binary_search_impl.c
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis/sp_structs.h
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis/topographic_map_impl.c
  neural_modelling/src/neuron/synapse_types/synapse_types_alpha_impl.h
  neural_modelling/src/neuron/synapses.c
Labels: bug, minor

#1212 n_atoms is defined in ApplicationVertex
  spynnaker/pyNN/models/abstract_models/abstract_population_settable.py
Labels: enhancement

#1219 Fixed location
  spynnaker/pyNN/external_devices_models/external_device_lif_control.py
  spynnaker/pyNN/external_devices_models/external_device_lif_control_vertex.py
  spynnaker/pyNN/external_devices_models/machine_munich_motor_device.py
  spynnaker/pyNN/external_devices_models/munich_spinnaker_link_motor_device.py
  spynnaker/pyNN/extra_algorithms/splitter_components/splitter_abstract_pop_vertex_fixed.py
  spynnaker/pyNN/extra_algorithms/splitter_components/splitter_abstract_pop_vertex_neurons_synapses.py
  spynnaker/pyNN/extra_algorithms/splitter_components/splitter_delay_vertex_slice.py
  spynnaker/pyNN/models/abstract_pynn_model.py
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/neuron/abstract_pynn_neuron_model.py
  spynnaker/pyNN/models/neuron/abstract_pynn_neuron_model_standard.py
  spynnaker/pyNN/models/neuron/population_machine_common.py
  spynnaker/pyNN/models/neuron/population_machine_local_only_combined_vertex.py
  spynnaker/pyNN/models/neuron/population_machine_vertex.py
  spynnaker/pyNN/models/neuron/population_neurons_machine_vertex.py
  spynnaker/pyNN/models/neuron/population_synapses_machine_vertex_common.py
  spynnaker/pyNN/models/neuron/population_synapses_machine_vertex_lead.py
  spynnaker/pyNN/models/neuron/population_synapses_machine_vertex_shared.py
  spynnaker/pyNN/models/populations/population.py
  spynnaker/pyNN/models/spike_source/spike_source_array.py
  spynnaker/pyNN/models/spike_source/spike_source_array_vertex.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_machine_vertex.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_variable.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_machine_vertex.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py
  spynnaker/pyNN/models/utility_models/spike_injector/spike_injector.py
  spynnaker/pyNN/models/utility_models/spike_injector/spike_injector_vertex.py
  spynnaker8/models/populations/population.py
  spynnaker_integration_tests/test_iobuf/test_only_cores_recorded/test_only_core_recording.py
  unittests/model_tests/neuron/test_abstract_neuron_impl.py
  unittests/model_tests/neuron/test_spike_source/test_spike_source_array_vertex.py
  unittests/model_tests/neuron/test_synaptic_manager.py
  unittests/test_populations/test_population.py
  unittests/test_populations/test_vertex.py
Labels: enhancement

#1220 Warning if SpikeSourceArray sends more that 100 spikes at one time.
  spynnaker/pyNN/models/spike_source/spike_source_array_vertex.py
  unittests/model_tests/neuron/test_spike_source/test_spike_source_array_vertex.py
Labels: minor

#1225 need len for some versions of numpy
  spynnaker/pyNN/models/spike_source/spike_source_array_vertex.py
Labels: bug, blocker

#1226 Iterate projections
  spynnaker/pyNN/extra_algorithms/splitter_components/splitter_abstract_pop_vertex_fixed.py
  spynnaker/pyNN/extra_algorithms/splitter_components/splitter_abstract_pop_vertex_neurons_synapses.py
  spynnaker/pyNN/models/neuron/population_machine_synapses.py
  spynnaker/pyNN/utilities/bit_field_utilities.py
Labels: bug

#1223 Single key_and_mask
  spynnaker/pyNN/models/neuron/key_space_tracker.py
  spynnaker/pyNN/models/neuron/local_only/local_only_convolution.py
  spynnaker/pyNN/models/neuron/local_only/local_only_pool_dense.py
  spynnaker/pyNN/models/neuron/population_synapses_machine_vertex_common.py
  spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
  spynnaker/pyNN/models/neuron/synaptic_matrices.py
  spynnaker/pyNN/models/neuron/synaptic_matrix.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_machine_vertex.py
  spynnaker/pyNN/models/utility_models/delays/delay_extension_machine_vertex.py
  spynnaker/pyNN/utilities/bit_field_utilities.py
Labels: enhancement
