Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2023-01, with the labels that each got.

#1268 Tidy up code with warnings in gcc v12.2
  neural_modelling/src/neuron/c_main_neurons.c
  neural_modelling/src/neuron/structural_plasticity/synaptogenesis/sp_structs.h
Labels: minor

#1266 Apply delay check correctly and increment skipped in mad impl
  neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_izhikevich_neuromodulation.c
  neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_mad_impl.c
  neural_modelling/src/neuron/synapses.c
Labels: bug

#1275 rate_and_count_per_slice
  spynnaker/pyNN/models/common/neuron_recorder.py
  spynnaker_integration_tests/test_selective_recording/test_sampling.py
Labels: bug, blocker

#1280 fix Clear bug
  spynnaker/pyNN/utilities/neo_buffer_database.py
  spynnaker_integration_tests/test_various/test_clear.py
Labels: bug

#1277 Treat IDMix like a PopulationView where possible.
  spynnaker/pyNN/models/populations/__init__.py
  spynnaker/pyNN/models/populations/idmixin.py
  spynnaker/pyNN/models/populations/population.py
  spynnaker/pyNN/models/populations/population_view.py
  unittests/test_pop_views_assembly/test_views.py
Labels: enhancement
