Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2023-04, with the labels that each got.

#1316 Make the code in setup_pynn better
  spynnaker/pyNN/setup_pynn.py
Labels: bug, minor

#1321 remove very old out of date diagrams
  spynnaker/pyNN/inheritance_diagrams/spynnaker_connections_inheritance_hirachy.dia
  spynnaker/pyNN/inheritance_diagrams/spynnaker_connections_inheritance_hirachy.png
  spynnaker/pyNN/inheritance_diagrams/spynnaker_edge_hirarchy.dia
  spynnaker/pyNN/inheritance_diagrams/spynnaker_edge_hirarchy.png
  spynnaker/pyNN/inheritance_diagrams/spynnaker_tool_chain_inheritance_hiarchy.png
  spynnaker/pyNN/inheritance_diagrams/spynnaker_vertex_inheritance_hiarchy.dia
  spynnaker/pyNN/inheritance_diagrams/spynnaker_vertex_inheritance_hiarchy.png
  spynnaker/pyNN/inheritance_diagrams/synnaker_tool_chain_inheritance_hiarchy.dia
Labels: bug

#1327 Improve github integration
  .github/dependabot.yml
  .github/workflows/c_actions.yml
  .github/workflows/publish.yml
  .github/workflows/python_actions.yml
Labels: bug, minor

#1332 Clean up of splitter code
  spynnaker/pyNN/external_devices_models/external_device_lif_control_vertex.py
  spynnaker/pyNN/extra_algorithms/splitter_components/splitter_abstract_pop_vertex_fixed.py
  spynnaker/pyNN/extra_algorithms/splitter_components/splitter_abstract_pop_vertex_neurons_synapses.py
  spynnaker/pyNN/extra_algorithms/splitter_components/splitter_delay_vertex_slice.py
  spynnaker/pyNN/extra_algorithms/splitter_components/splitter_poisson_delegate.py
  spynnaker/pyNN/models/neuron/abstract_population_vertex.py
  spynnaker/pyNN/models/neuron/abstract_pynn_neuron_model.py
  spynnaker/pyNN/models/spike_source/spike_source_array.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_variable.py
  spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
  spynnaker/pyNN/models/utility_models/spike_injector/spike_injector.py
Labels: minor
