Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2023-02, with the labels that each got.

#1287 Fix STDP triplet rule and add test
  spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/timing_dependence_pfister_spike_triplet.py
  spynnaker_integration_tests/test_stdp/test_STDP_triplet_additive.py
Labels: bug

#1243 Ds per reset
  spynnaker_integration_tests/test_debug_mode/check_debug.py
  unittests/test_using_virtual_board/test_debug_mode/test_debug.py
Labels: enhancement

#1291 Update CSA block test
  unittests/connector_tests/test_csa_connector.py
Labels: bug

#1292 Spalloc server jdbc
  spynnaker_integration_tests/conftest.py
  spynnaker_integration_tests/scripts/pattern_spiker.py
  spynnaker_integration_tests/test_additional_params_on_pop_not_recogonised/test_additional_params_mix.py
  spynnaker_integration_tests/test_additional_params_on_pop_not_recogonised/test_additional_params_needed.py
  spynnaker_integration_tests/test_additional_params_on_pop_not_recogonised/test_additional_params_not_needed.py
  spynnaker_integration_tests/test_auto_pause_and_resume_tests/test_medium_fail_run/test_synfire_low_sdram_medium_run.py
  spynnaker_integration_tests/test_connectors/test_connectors.py
  spynnaker_integration_tests/test_connectors/test_fixed_number_post_connector.py
  spynnaker_integration_tests/test_connectors/test_fixed_number_pre_connector.py
  spynnaker_integration_tests/test_record_sdram/test_record_no_projections.py
  spynnaker_integration_tests/test_record_sdram_no_extra_mons/test_record_no_projections.py
  spynnaker_integration_tests/test_selective_recording/test_recording_on_off.py
  spynnaker_integration_tests/test_selective_recording/test_sampling.py
  spynnaker_integration_tests/test_stdp/test_multiple_stdp_mechs_on_same_neuron.py
  spynnaker_integration_tests/test_various/test_models.py
  spynnaker_integration_tests/test_various/test_projections_between_runs.py
  unittests/test_pop_views_assembly/test_models.py
  unittests/test_pop_views_assembly/test_record.py
Labels: bug, enhancement

#1296 Fix pushbot
  spynnaker/pyNN/external_devices/__init__.py
  spynnaker/pyNN/external_devices_models/abstract_multicast_controllable_device.py
  spynnaker/pyNN/external_devices_models/push_bot/abstract_push_bot_retina_device.py
  spynnaker/pyNN/external_devices_models/push_bot/ethernet/push_bot_device.py
  spynnaker/pyNN/external_devices_models/push_bot/ethernet/push_bot_retina_connection.py
  spynnaker/pyNN/external_devices_models/push_bot/ethernet/push_bot_retina_device.py
  spynnaker/pyNN/external_devices_models/push_bot/ethernet/push_bot_wifi_connection.py
  spynnaker/pyNN/external_devices_models/push_bot/parameters/push_bot_retina_viewer.py
  spynnaker/pyNN/external_devices_models/push_bot/spinnaker_link/push_bot_retina_device.py
  spynnaker/pyNN/external_devices_models/threshold_type_multicast_device_control.py
  spynnaker/pyNN/protocols/munich_io_spinnaker_link_protocol.py
Labels: bug

#1258 Fixes pool dense connector in many ways
  neural_modelling/src/neuron/local_only/local_only_conv_impl.c
  neural_modelling/src/neuron/local_only/local_only_pool_dense_impl.c
  spynnaker/pyNN/external_devices_models/spif_retina_device.py
  spynnaker/pyNN/models/abstract_models/has_shape_key_fields.py
  spynnaker/pyNN/models/neural_projections/connectors/convolution_connector.py
  spynnaker/pyNN/models/neural_projections/connectors/pool_dense_connector.py
  spynnaker/pyNN/models/neuron/local_only/local_only_convolution.py
  spynnaker/pyNN/models/neuron/local_only/local_only_pool_dense.py
  spynnaker/pyNN/models/utility_models/spike_injector/spike_injector_vertex.py
Labels: bug

#1297 Fix pool dense odd
  neural_modelling/src/neuron/local_only/local_only_pool_dense_impl.c
  spynnaker/pyNN/models/neural_projections/connectors/pool_dense_connector.py
  spynnaker_integration_tests/test_local_only/test_pool_dense_odd.py
Labels: bug, enhancement, blocker
