Repository SpiNNakerManchester/sPyNNaker, pull requests merged in 2023-03, with the labels that each got.

#1299 Rename LICENSE.md
  LICENSE_POLICY.md
Labels: minor, next_release

#1305 fix getdata clear on previous segment Clear
  spynnaker/pyNN/models/recorder.py
  spynnaker/pyNN/utilities/neo_buffer_database.py
  spynnaker_integration_tests/test_various/test_clear.py
Labels: blocker

#1312 Push bot viewer
  spynnaker/pyNN/external_devices_models/push_bot/parameters/push_bot_retina_viewer.py
  spynnaker/pyNN/external_devices_models/push_bot/spinnaker_link/push_bot_retina_device.py
Labels: enhancement
